### ISSUE TITLE
Error initializing the player engine.

### ISSUE THREAD

**Issue by ThereThatGuy** [adammhaile/Elpis#102]
Just tried to launch Elpis and recieved this error. I've not really changed anything. Any help would be great!

POS: Win 10 x64

http://puu.sh/lHYTS/dff6fdad5f.png

BassPlayer.BassException: Cannot find an output device matching description [Headphones (Realtek High Definition Audio)]
   at BassPlayer.BassAudioEngine.ChangeOutputDevice(String newOutputDevice)
   at Elpis.MainWindow.FinalLoad()

**Comment by seliver** [comment]
Which version are you using? Try installing the beta, your issue might be related to having wrong information about the output device in the config file.

----- Mensagem Original -----
De: "ThereThatGuy" <notifications@github.com>
Enviado: ‎03/‎12/‎2015 16:44
Para: "adammhaile/Elpis" <Elpis@noreply.github.com>
Assunto: [Elpis] Error initializing the player engine. (#102)

Just tried to launch Elpis and recieved this error. I've not really changed anything. Any help would be great!
POS: Win 10 x64
http://puu.sh/lHYTS/dff6fdad5f.png
BassPlayer.BassException: Cannot find an output device matching description [Headphones (Realtek High Definition Audio)]
at BassPlayer.BassAudioEngine.ChangeOutputDevice(String newOutputDevice)
at Elpis.MainWindow.FinalLoad()

**Comment by ThereThatGuy** [comment]
Using Version 1.5.1, Updated to the beta 1.5.2, Same thing. What is the LOC of the ini config file so I can edit that, I think you are correct.
