### ISSUE TITLE
Taskbar tooltip doesn't display ampersands correctly

### ISSUE THREAD

**Issue by Wires77** [adammhaile/Elpis#104]
If the song or artist name has '&' in it, the '&' won't display.

I found this link that might explain why: https://social.msdn.microsoft.com/Forums/en-US/d9beadba-62b3-4888-abb2-79c72853e840/ampersand-and-strings?forum=winforms

**Comment by Wires77** [comment]
Also just found this:  http://www.codeproject.com/Articles/4993/Windows-balloon-tool-tip-and-the-taskbar-notificat which mentions a "TTS_NOPREFIX" setting which prevents stripping of the ampersand from a tooltip.

I would probably take a swing at this myself if I had a copy of Visual Studio to work on this.

**Comment by seliver** [comment]
Hi. Thanks for reporting. 
Btw, there is a free community version of visual studio, check it out : https://www.visualstudio.com/en-us/downloads/download-visual-studio-vs.aspx
