### ISSUE TITLE
Idea to add more variety

### ISSUE THREAD

**Issue by pgorbas** [adammhaile/Elpis#105]
Here is an idea that would force Pandora to play a bigger variety of songs.

In the options put in a check-box "Force variety " with help text : " Forces Pandora to play a larger variety of song by marking each title 'Tired of this song'  when played  ".

Then, implement it, as the help text indicates, by sending Pandora the "I'm tired of this song" flag after each song is played.  This will ensure the same song will not be played more than once in any 30 day period...

**Comment by seliver** [comment]
This is probably not a viable thing to do. Please try and see if marking every song manually will indeed bring you new songs or just stop de playback.

**Comment by pgorbas** [comment]
Really?   I haven't examined the source code but it seams straight forward enough to me to simulate the user clicking the tired of this song option whenever a new song starts playing. 

Unless you think it would cause problems with Pandora. I could Probally do it myself if I had the time. 

Taking the time to manually click the option after every song plays is easy too disruptive to my work. 

Reguards, Paul Gorbas

<div>-------- Original message --------</div><div>From: seliver <notifications@github.com> </div><div>Date:01/24/2016  6:24 PM  (GMT-06:00) </div><div>To: adammhaile/Elpis <Elpis@noreply.github.com> </div><div>Cc: fubar <pgorbas@yahoo.com> </div><div>Subject: Re: [Elpis] Idea to add more variety (#105) </div><div>
</div>This is probably not a viable thing to do. Please try and see if marking every song manually will indeed bring you new songs or just stop de playback.

**Comment by seliver** [comment]
It is pretty straight forward indeed, but I feel that your account might be suspended for marking all songs as tired of.

**Comment by pgorbas** [comment]
Good point, I’ll bounce that question off of Pandora and see what they say.

**Comment by Wires77** [comment]
@pgorbas I'm closing this and will reopen if you have an update from Pandora.
