### ISSUE TITLE
HTTP API Enhancements (Cover art and more data)

### ISSUE THREAD

**Issue by mneimeyer** [adammhaile/Elpis#109]
I'm dabbling in creating a web interface for Elpis for my cell phone. As it stands I can control Elpis but I don't have enough to give it a "player" interface. Would it be possible to get the following things added to the HTTP API?

1. A way to get the current cover art of the playing song. Perhaps something like /coverart which would return an actual JPG or PNG or anything really...

2. A way to get the current position and duration. Perhaps something like /currentposition which would return a string like "2:45/5:23" to indicate 2:45 into a song that is 5:23 long.

3. A way to get the current artist and album. Perhaps something like /currentartist and /currentalbum to align with /currentsong?

Conversely, maybe a single "/getcurrentsonginfo" that returns everything known about the song except the binary image?

I apologize for the length but I really love Elpis and while I would love to contribute directly my strengths do not lie in building Windows Apps...

Thanks!

**Comment by seliver** [comment]
Hi.
Check the wiki: https://github.com/adammhaile/Elpis/wiki/HTTP-Api
/currentsong gives you almost all info you need. Also check the implementation of the android app where I used the http API: https://github.com/seliver/ElpisRemote
