### ISSUE TITLE
Double Like = No Like

### ISSUE THREAD

**Issue by eriqs** [adammhaile/Elpis#110]
First of all, THANKS - this is an awesome app that I wish I had discovered sooner! :)

My one gripe is that I keep it minimized to the tray, and right-click to like tracks - but there is currently no way to tell if you have already liked that track, and if you choose to like a track which you have previously liked, it removes that like.  If nothing else, it would be nice if there was a check mark next to 'Like' when the track is already liked...

Thanks again! :+1:

**Comment by adammhaile** [comment]
The thumb icon *should* be highlighted after you have already liked a
track... even at a later time when the same track comes up in a station.
So, either you are not seeing that the thumb icon is a brighter shade or
pandora is no longer sending the data that specifies the track is already
liked....

**Comment by eriqs** [comment]
It's definitely not highlighted, at-least not in the tray:

[image: Inline image 1]

[image: Inline image 2]

Thanks,
Eriq

**Comment by adammhaile** [comment]
Oh... yeah. It's not in the tray. Good point. That could probably be
updated. Should be in the app itself.

**Comment by eriqs** [comment]
It is - I included screenshots in my last email, but not sure if they came
through.  Again, my specific issue is that I keep it minimized to the tray,
and can't see that it's already been liked - so when I click like, it
unlikes it.

Thanks,
Eriq

**Comment by nwhansen** [comment]
I would also like to second something along those lines. I keep the application minimized to tray and use shortcuts to like/dislike a song. I have to watch the text to know if I accidentally un-liked a song. It would be nice to have that as a setting or maybe be able to program an "unlike" but don't dislike button or configuration. I would also like to second the awesome work you have done. I used to use pianobar with a hodgepodge of AutoHot keys to get a usable experience this is just seemless :) :+1:

**Comment by Wires77** [comment]
This is probably related to #72 as well, especially @nwhansen's comment

**Comment by seliver** [comment]
What should I do here? Make the unlike action (action != dislike) only possible from the GUI instead of this being available everywhere?

**Comment by eriqs** [comment]
There's a 'Dislike Song' option in the system tray - that should stay.  But
clicking 'Like Song' option on a song you've already liked should-not have
any effect.

Thanks,
Eriq

**Comment by tremblane** [comment]
My suggestion: if a song has been liked, the system tray menu should change the "Like" option to "Un-Like". That gives an indicator that the song has already been like, while keeping the ability to remove the like without opening the GUI.

**Comment by Wires77** [comment]
I just merged a commit using @tremblane 's suggestion.
