### ISSUE TITLE
Windows 10 Notification icon is pixelated

### ISSUE THREAD

**Issue by Wires77** [adammhaile/Elpis#113]
When playing or pausing a song, the icon comes up pixelated.  This is version 1.5.0
![blurryicon](https://cloud.githubusercontent.com/assets/1209372/13034112/c5533482-d2e9-11e5-98e5-12be1c844cb0.PNG)

**Comment by seliver** [comment]
I'm not sure which icon Win10 uses for the notifications. The strange thing is that the icon has got a black background, I thought this was corrected in 1.4.7. Will have a look.

**Comment by jevdemon** [comment]
Possibly related, notifications aren't working for me.  Windows 10 OS Build 10.586.164.
Love this app, thanks for working on it.

**Comment by hhocker** [comment]
@seliver not sure if you are looking into this but I am pretty sure that the notifications use the tray icon. The black background is probably caused due to a transparency issue. Not sure if we can get a higher res tray icon or not for the next release.

**Comment by seliver** [comment]
Later will try to use the big icon on the tray to see how it goes.
