### ISSUE TITLE
How to update to 1.5.2 if using the portable version of 1.5.0?

### ISSUE THREAD

**Issue by giantspeck** [adammhaile/Elpis#115]
I have the portable version of 1.5.0 installed on my work computer and each time I open it, it prompts me to update to 1.5.2.  My work network won't let me update it from the app itself and you haven't released a portable version for 1.5.2, so I was wondering if there's an easy way of making 1.5.2 portable or updating the necessary files in 1.5.0.

**Comment by seliver** [comment]
Ok, I will make a portable version of 1.5.2 and will let you know ;)

**Comment by seliver** [comment]
Heii.
Finally remembered to do the portable version. Check it out here: https://github.com/adammhaile/Elpis/releases/tag/1.5.2

To make a portable version of Elpis is pretty straightforward, just zip the Elpis installation folder and it's done.
