### ISSUE TITLE
Crashes upon clicking 'settings' button

### ISSUE THREAD

**Issue by narfman0** [adammhaile/Elpis#116]
In Elpis 1.5.0, 1.5.0 portable, 1.5.1 and 1.5.2 when I click the settings button I get a crash. A windows modal comes up "Elpis has stopped working" "A problem caused the program to stop working correctly. Windows will close the program and notify you if a solution is available." Is there a dump i can upload?

Newly formatted machine, fully updated through windows update. Installed .net 4.6.1. It worked before the format. I don't have space to install visual studio - perhaps a debug .net runtime..?

**Comment by seliver** [comment]
Try installing the version 4.5.

----- Mensagem Original -----
De: "Jon Robison" <notifications@github.com>
Enviado: ‎04/‎03/‎2016 18:38
Para: "adammhaile/Elpis" <Elpis@noreply.github.com>
Assunto: [Elpis] Crashes upon clicking 'settings' button (#116)

In Elpis 1.5.0, 1.5.0 portable, 1.5.1 and 1.5.2 when I click the settings button I get a crash. A windows modal comes up "Elpis has stopped working" "A problem caused the program to stop working correctly. Windows will close the program and notify you if a solution is available." Is there a dump i can upload?
Newly formatted machine, fully updated through windows update. Installed .net 4. It worked before the format. I don't have space to install visual studio - perhaps a debug .net runtime..?

**Comment by narfman0** [comment]
Hmm the installer comes up with embedded dialog "Same or higher version of .NET Framework 4.5 has already been installed on this computer."

**Comment by narfman0** [comment]
Settings.xaml.cs:127 "IPHostEntry host = Dns.GetHostEntry(Dns.GetHostName());"  is throwing "An unhandled exception of type 'System.Net.Sockets.SocketException' occurred in System.dll". I bet my dns is not set up very well for this, however, it'd be great to add some exception handling to make this more graceful.
