### ISSUE TITLE
error initializing the player engine, usb sound device

### ISSUE THREAD

**Issue by jwd007** [adammhaile/Elpis#119]
i read the config file has changed for  the bassException. i include my error if different.
How do i get around this ? 

BassPlayer.BassException: Cannot find an output device matching description [Speakers (USB PnP Sound Device)]
   at BassPlayer.BassAudioEngine.ChangeOutputDevice(String newOutputDevice)
   at Elpis.MainWindow.FinalLoad()

**Comment by brandylynn8403** [comment]
I got the same one when i plugged in my New usb Headset. Updated drivers and uninstalled and reinstalled drivers. 

BassPlayer.BassException: Cannot find an output device matching description [Speakers / Headphones (IDT High Definition Audio CODEC)]
   at BassPlayer.BassAudioEngine.ChangeOutputDevice(String newOutputDevice)
   at Elpis.MainWindow.FinalLoad()

**Comment by seliver** [comment]
same as #120. closing.
