### ISSUE TITLE
GUI Missing in Windows 10 v1511 10586.164

### ISSUE THREAD

**Issue by zogato** [adammhaile/Elpis#124]
Operating System: Windows 10 x64 v1511 10586.164

Current Elpis Version: 1.5.2

Using proxy/vpn: No

Steps to reproduce the problem: Hard to reproduce, GUI is now completely missing after working beforehand.

Problem: GUI has completely disappeared. I am only able to control Elpis using the system tray context menu.

Application can only be "seen" when alt tabbing.
![capture](https://cloud.githubusercontent.com/assets/1133300/14430369/5157143c-ffcf-11e5-819c-ea511f60a5a0.PNG)

**Comment by seliver** [comment]
Try deleting the config file and starting Elpis again.

**Comment by zogato** [comment]
Hey that worked! Thanks! 

Navigated to C:\Users\<User>\AppData\Roaming\Elpis
and deleted the elpis.config file.
