### ISSUE TITLE
Media hotkeys not working

### ISSUE THREAD

**Issue by eriqs** [adammhaile/Elpis#125]
I have several Microsoft Wireless Desktop sets, and the media hotkeys do-not work for controlling Elpis.  I'm currently using a Microsoft Wireless Laser Keyboard 6000 v2.0 with Microsoft Mouse and Keyboard Center version 2.7.133.0 and have confirmed that they buttons are set to their defaults in MMKC (Play/Pause, Previous Track and Next Track).  The Elpis hotkeys are also set to their defaults (I renamed the config file to reset them after trying to make them work).

**Comment by seliver** [comment]
this is the same issue as #40. closing.
