### ISSUE TITLE
Notification sounds on Win10

### ISSUE THREAD

**Issue by hanthor** [adammhaile/Elpis#126]
Every time you play/pause, next song, or if it goes to the next track, it plays the sound. this is odd behaviour and I wonder if it is a bug.

**Comment by seliver** [comment]
What sound are you talking about?

**Comment by hanthor** [comment]
When you press the hotkey for play/pause or skip, it will resume playback
but with also play a Windows notification sound.

**Comment by seliver** [comment]
Never heard of this. Maybe it's happening because of your setup.

**Comment by telmer6** [comment]
This also happens to me. I think it's an OS behavior, as W10 dings on all notifications I've noticed.

If that's the case, not much to do but disable notifications.

**Comment by hanthor** [comment]
Other music applications do not do it. I don't know their method, but I know for a fact the GPMDP has silent notifications

**Comment by telmer6** [comment]
And that's using the W10 toast notifications?

**Comment by telmer6** [comment]
You learn something new every day. The toast sound can be muted/changed on a per-application basis:

https://msdn.microsoft.com/en-us/library/windows/apps/br230849.aspx

**Comment by seliver** [comment]
Ok then, not an Elpis issue but a windows 10 "problem". Marking this as solved then 👍
