### ISSUE TITLE
Feature Request: Taskbar Controls

### ISSUE THREAD

**Issue by telmer6** [adammhaile/Elpis#127]
It'd be lovely if you could mirror the controls you get from the system tray menu (play/pause, skip, like, dislike) to the taskbar a la WMP or Groove.

**Comment by seliver** [comment]
I'm not quite sure what you are talking about. Can you give an image example?

**Comment by telmer6** [comment]
Windows Media Player's taskbar controls: http://i.stack.imgur.com/Cq4CL.jpg

**Comment by seliver** [comment]
Is this used in windows 10?

**Comment by telmer6** [comment]
Yes; it appears in Microsoft's Groove player (W10).

**Comment by seliver** [comment]
Well then, it can be considered a long-term todo.
