### ISSUE TITLE
Proxy usage clunky

### ISSUE THREAD

**Issue by vassijoseph** [adammhaile/Elpis#128]
Operating System: Windows 7 sp1 Ultimate X64

Current Elpis Version: 1.5.2

Using proxy/vpn: yes

Steps to reproduce the problem: When using proxy the program waits until you reach the part where the songs are playing to do anything else.
That means sometimes when the proxy is slowed down I have to wait for a few minutes to do anything, even change the proxy to a more stable one.
It would be better to have access to the settings from the very start.

Problem:

**Comment by seliver** [comment]
If you haven't got a stable proxy, probably the best thing for you to do is to change the proxy settings directly in the config file. This way if you see that the loading is too slow, you can Alt-F4 Elpis and look for another proxy. When found, paste the settings to config file and start Elpis again.

**Comment by vassijoseph** [comment]
This is certainly more viable but the problem remains and not many people would be willing to go into so much trouble.

Thanks for your suggestion nonetheless.
