### ISSUE TITLE
HIgh-DPI Support

### ISSUE THREAD

**Issue by seliver** [adammhaile/Elpis#13]
Operating System Version?: Windows 8.1, 64-bit

Elpis Version?: 1.4.5

Country and do you use a Proxy?: USA; no

What steps will reproduce the problem?
1. Open Elpis on a high-DPI screen.

What is the expected output? What do you see instead?:
Elpis fails to show the full window on high-dpi displays. I am on a laptop with a resolution of 3200x1800 and the way my maximized Elpis window appears is attached. Only the content near the left side is visible.
![capture](https://cloud.githubusercontent.com/assets/7545867/5741797/7b21deac-9c05-11e4-89c9-6da5dd506b65.PNG)

comment 1 iv5970
Same OS + resolution (Yoga 2 Pro), same issue. I'm comfortable with C# but have pretty limited experience with WPF; does anyone have an idea of what it takes to make WPF applications scale properly? One gorgeous HiDPI app one could use as an example of 3rd-party applications done right would be GitHub For Windows (the new version). Sublime Text 3 and BitTorrent Sync are two other great examples that I happen to have up at the moment.

I'm wondering if going with a system-standard UI instead of the light-on-dark custom theme would help this flow properly?

comment 2 iv5970
One other thing I'll note, setting the "Ignore DPI on HiDPI screens" or whatever option in the exe properties half-works for a short while. The window will display properly, in full, until it is moved, resized, or minimized, at which time it returns to what it looks like in OP's screenshot.

comment 3 rsanek
Unfortunately I'm in the same position - I love the app and would really like to be able to contribute, but my technical knowledge just isn't there for C# or WPF and I don't really have the time to learn it right now. Perhaps we will find a maintainer soon; if not, I might take a shot at in early next year.

**Comment by gundermanc** [comment]
I submitted fix for this issue that should scale appropriately. Turns out that native Win32 apps are not inherently High DPI aware unlike WPF and any interop with Win32 has to be scaled.

Great app, thanks :) is there any way I can get involved in future work?

**Comment by seliver** [comment]
Great! Glad you like it!

Thanks for your help :) Will later have a look at the code to merge it.

You can always get involved in any issue already created or submit any 
new bug reports/enhancements/etc. Just make a pull request and I'll 
merge it ;)
And as always, all help is highly appreciated :)

Às 07:15 de 13/08/2015, Christian Gunderman escreveu:
