### ISSUE TITLE
Elpis doesn't seem to play nice with the Win32 event loop?

### ISSUE THREAD

**Issue by yumaikas** [adammhaile/Elpis#135]
Elpis doesn't seem to respond to WinKey+Arrow commands for moving a window around monitors. Is there any known reason for this?

**Comment by Torvin** [comment]
@yumaikas win+arrows combinations only work for windows that have 'maximise' button. to move Elpis around monitors use win+shift+arrows.

**Comment by yumaikas** [comment]
Very interesting. I'll try this out soon. @Torvin Do you happen to know where one would find out about such things, or is it just Windows Tribal Lore (TM), as it were?

**Comment by Torvin** [comment]
@yumaikas try something like this: https://support.microsoft.com/en-nz/help/12445/windows-keyboard-shortcuts

**Comment by Wires77** [comment]
Thanks @Torvin , I'm going to close this, especially with a possible UI revamp being discussed.

**Comment by Torvin** [comment]
Oo, a UI revamp would be nice!
