### ISSUE TITLE
Feature: Minimize to Tray, X still exits.

### ISSUE THREAD

**Issue by AbeFM** [adammhaile/Elpis#136]
I have a suggestion/request: Can you separate out "minimize to tray" and "close to tray"? If I want to quit a program, I want to quit it. There already IS a minimize button. Alternatively, a "to tray" button could be added though it seems confusing to me.

Really love the program, cleans up my desktop!!

**Comment by AbeFM** [comment]
![image](https://cloud.githubusercontent.com/assets/42385/16353917/2addcb04-3a38-11e6-8df8-754fed5bbf11.png)

Personally. I feel close should always be close, and the option should be on minimize, but some people perhaps expect close to.... not close. :-)

**Comment by Wires77** [comment]
This seems like a good suggestion and we've seen it before in #37 .  I'm going to close this as a duplicate and prioritize it a little higher.  Feel free to make a pull request for it and I'll accept it though

**Comment by AbeFM** [comment]
Can you tell me how to get 100% *OFF* this list?
