### ISSUE TITLE
"Error initializing the player engine" when output device is no longer available.

### ISSUE THREAD

**Issue by jhfry** [adammhaile/Elpis#137]
I use Elpis specifically because the Pandora web client lacks the ability to choose an alternate output.  I like to listen to music on my desktop speakers while game/system sounds come out my headset.

I use Elpis on a laptop with a docking station that has my desktop speakers attached.  If I unplug the speakers, or undock my laptop I cannot start Elpis.  I imagine this issue would arise whenever the application was using an output device that is no longer available.

I think proper behavior in this case should be to load the settings screen and ask the user to select a new output device.

I realize that I can probably delete the config file to get it working... but this seems like overkill to me because this is a common use scenario.

**Comment by seliver** [comment]
This issue should be solved on 1.6.0. Already discussed here: #77
