### ISSUE TITLE
Elpis not using local hosts name resolution

### ISSUE THREAD

**Issue by Lokydoki** [adammhaile/Elpis#146]
Hi, as an islander outside the US I use portaller (http://www.portaller.com) which is awesome to bypass country restriction.

At home I am able to change my dns to use portaller's DNS. Elpis works great.
At work, since I can't change my default DNS on computer (because i'm using entreprise internal DNS servers) I used to trick it by adding *.pandora.com and www.pandora.com to local hosts file and it works great too in browsers !

My problem is that ELPIS seems to ignore local name resolution thus I'm unable to use my trick with local host.

If this gets resolved I think it should be benefit numerous nonUS resident !

Any hint to force local name resolution or is a patch/evolution is mandatory ?

Thanks !

**Comment by Lokydoki** [comment]
After a few tests with source code it appears that elpis is resolving from localhost file correctly. 
I was missing this resolution : 
107.170.15.247	tuner.pandora.com

Works great now !

**Comment by seliver** [comment]
👍
