### ISSUE TITLE
Pandora Plus features

### ISSUE THREAD

**Issue by Silun** [adammhaile/Elpis#149]
Pandora One has become Pandora Plus, and with the name change came a few new features that are currently not available in Elpis. They include a replay feature, which allows the user to go back in the history of the songs played this session and press the replay button, which will queue that song again and begin to play it instantly. They have also added support for offline listening.

I have also noticed that the loudness of different songs is relatively close when played on official Pandora apps or the web browser. However, in Elpis there is often a noticeable, quite large difference in loudness, requiring slider adjustment. I'm not sure what happens there, maybe Pandora utilizes peak normalization or [replaygain](http://wiki.hydrogenaud.io/index.php?title=ReplayGain)?

In any case, thanks for your work! Love the player.

**Comment by Wires77** [comment]
I think this is probably too close to downloading Pandora's songs for us to implement.  We don't need an additional reason for them to shut this project down.
