### ISSUE TITLE
Icons can not be seen on a tray witha dark/black background.

### ISSUE THREAD

**Issue by seliver** [adammhaile/Elpis#15]
Operating System Version?: Windows 7 H.P. 64-bit

Elpis Version?: 1.4.5.0

Country and do you use a Proxy?: USA, no.

What steps will reproduce the problem?
1. Set a wallpaper or background color that is dark or black on the edge at the system tray.
2. Open Control Panel > Personalization > Window Color and Appearance, and select the checkbox for "Enable Transparency"
3. Move the "Color Intensity" slider around to adjust the transparency level and observe at what levels the Elpis tray icon is visible or not.

What is the expected output? What do you see instead?: The Elpis icon is no longer visible when the slider is in the left 2/3 of the range.

**Comment by j2xl** [comment]
I see this as well in the taskbar: with a dark background, the Elpis program icon appears as a blank space between program icons.

**Comment by seliver** [comment]
Can you send a printscreen of this?

**Comment by j2xl** [comment]
This is what my taskbar looks like with a dark background and labels hidden. Elpis is the 10th small icon from the left.

![taskbar-labels-hidden](https://cloud.githubusercontent.com/assets/3752878/5966518/0a62fc44-a7ba-11e4-8bb9-84dd61f6395b.png)

**Comment by Wires77** [comment]
Looks like a simple change to the icon (i.e. adding a white border) would be just fine to fix this.

**Comment by seliver** [comment]
Yea, that's exactly what it is needed to be done.
I have played with paint.net a little, what do you think?
![main_icon](https://cloud.githubusercontent.com/assets/7545867/5967749/4eb389ce-a808-11e4-913e-c4fe672f9996.png)

**Comment by seliver** [comment]
I don't think that this one looks good at all. Have a look at this:
![capturar](https://cloud.githubusercontent.com/assets/7545867/5967952/4b9f2a0c-a80a-11e4-9ffc-dcb535518edf.JPG)
![capturar2](https://cloud.githubusercontent.com/assets/7545867/5967953/4ba7a51a-a80a-11e4-9ebe-6b59cc8a59cc.JPG)

**Comment by SoullessWaffle** [comment]
How about adding a white/colored background, while keeping the note icon black or a dark grey?

**Comment by seliver** [comment]
It's an idea, but it doesn't look so well as a desktop shortcut
![capturar](https://cloud.githubusercontent.com/assets/7545867/5968406/0cad77d6-a80f-11e4-83f5-bfda8d80e207.JPG)
![capturar2](https://cloud.githubusercontent.com/assets/7545867/5968407/0cb23fe6-a80f-11e4-8ab1-42cb3365664c.JPG)
![capturar3](https://cloud.githubusercontent.com/assets/7545867/5968408/0cb53868-a80f-11e4-92f5-79d46370d2ab.JPG)
Anyway, if anyone could contribute with a new icon(or all icons :) ), that would be great, because these icons were meant to be temporary.

**Comment by seliver** [comment]
@SoullessWaffle What do you think of the icon with the white background?

**Comment by SoullessWaffle** [comment]
@seliver I agree that it doesn't look great when scaled down to icon resolution. Designing a new icon from scratch might indeed be best.
My own graphics design skills are rather lacking, but I've heard good things about [fiverr][1].
[1]: https://www.fiverr.com/search/gigs?acmpl=1&sub_category=49&category=3&utf8=%E2%9C%93&search_in=category&query=Icon&page=1&layout=auto&filter=rating

**Comment by seliver** [comment]
Ok, had some work around the image, tell me what you think:
![main_icon](https://cloud.githubusercontent.com/assets/7545867/6067116/184fa95a-ad6a-11e4-93a3-5806428a3d7d.png)
![1](https://cloud.githubusercontent.com/assets/7545867/6067166/6d1b62b2-ad6a-11e4-8518-9f482b6cd225.JPG)
![2](https://cloud.githubusercontent.com/assets/7545867/6067167/6d1e8d7a-ad6a-11e4-993d-723eceba2c3c.JPG)

**Comment by seliver** [comment]
Or this version:

![main_icon](https://cloud.githubusercontent.com/assets/7545867/6067353/b5690622-ad6b-11e4-8835-fdfcb8cef744.png)
![1](https://cloud.githubusercontent.com/assets/7545867/6067355/b80f17a4-ad6b-11e4-8b97-9028adf34892.JPG)
![2](https://cloud.githubusercontent.com/assets/7545867/6067358/b9972a30-ad6b-11e4-9fb3-7b8479f6c55d.JPG)

**Comment by SoullessWaffle** [comment]
The second version looks better when scaled down, but it looks like it is partly cut off at the top and bottom edges.

**Comment by adammhaile** [comment]
What about this?

![elpis_logo](https://cloud.githubusercontent.com/assets/957162/6073722/4ecb75ac-ad80-11e4-96e2-aafd60e1703d.png)

**Comment by SoullessWaffle** [comment]
That actually looks pretty great. I'm surprised I didn't think of that :)

**Comment by seliver** [comment]
It does looks really good, Adam. Here's how it looks like on the task bar.
![1](https://cloud.githubusercontent.com/assets/7545867/6081295/5f540d36-ae10-11e4-933d-65d2a8c15128.JPG)
![2](https://cloud.githubusercontent.com/assets/7545867/6081294/5f5214c2-ae10-11e4-8b63-9096d405fbe4.JPG)
Will make a commit with this new icon.

**Comment by adammhaile** [comment]
Nice!

**Comment by seliver** [comment]
Can anyone have a look at this while the 7 free days have not expired yet? https://www.graphicstock.com/freeimages
Maybe something good can be found. I currently have no time for that :(
