### ISSUE TITLE
Elpis_StartupLocation|2158,0

### ISSUE THREAD

**Issue by mancoast** [adammhaile/Elpis#152]
Hello,

I am experience a multi-screen glitch that occurs under a unique scenario, but can always be recreated.

1.) Desktop has 2+ monitors connected and configured.
2.) Remote into Desktop and open Elpis.
3.) Physical access Desktop after RDP session, Elpis window startup location is now invalid.

FIX:
Validation of Config parameter: Elpis_StartupLocation.
Requires: Elpis_StartupLocation.X < DesktopResolution.X
Requires: Elpis_StartupLocation.Y < DesktopResolution.Y

IMPLEMENT:
Perform a validation check of Elpis_StartupLocation on Application Entry.

Thanks,
coast

**Comment by Wires77** [comment]
This should be fixed in the beta version already.  I'll be doing a full release soon, so let me know if you still see this issue after that.

**Comment by mancoast** [comment]
@Wires77 Thanks!
