### ISSUE TITLE
Cant access settings

### ISSUE THREAD

**Issue by sirbogs** [adammhaile/Elpis#153]

**Comment by seliver** [comment]
What happens when you click on settings?

**Comment by sirbogs** [comment]
No popup So you have no access to anything.

right click on taskbar icon an that's the extent of what I can do. Its a 
radio with channel selection

been like this since I upgraded to windows 10... Keep waiting for a fix

Using newest version ... did an uninstall empty folder and reinstalled

haven't tried going to an older version

any suggestions appreciated
:)

**Comment by seliver** [comment]
Try deleting the configuration files. They're located at
C:\Users\<YOUR_USERNAME>\AppData\Roaming\Elpis

The file to rename(just in case you might need the old configuration) is
the elpis.config
After that just try to open Elpis again.

**Comment by sirbogs** [comment]
Yep that solve the problem

Thanks

BTW
I love this program :)
