### ISSUE TITLE
Indicate like/dislike in tray icon right-click menu

### ISSUE THREAD

**Issue by jrittenh** [adammhaile/Elpis#162]
I haven't looked into the Pandora API, so I don't know if this is possible, but if you're able to query for like/dislike status, it would be nice to see that in the right-click menu.  In general, I would assume you'd only be querying for likes, but if you dislike and it won't let you skip, a mark there would be nice to indicate that it registered.

**Comment by Wires77** [comment]
I have something like this on my local machine.  How does that look?
![songlike](https://cloud.githubusercontent.com/assets/1209372/24834620/d7506d6e-1cb0-11e7-995e-986fcce076f8.PNG)

**Comment by jrittenh** [comment]
That's pretty much exactly what I was looking for.

**Comment by Wires77** [comment]
Implemented in #169
