### ISSUE TITLE
1.6.0 Installer Requires Killing old Elips Process

### ISSUE THREAD

**Issue by thomaswp** [adammhaile/Elpis#183]
Thanks for the 1.6 update! If I launch Elpis 1.5, it prompts me to install it. When I say yes, it downloads and runs the installer, which goes fine until some point when it tells me there's a process running (elpis.exe) that's using needed resources. I have to go into Task Manager and end the process to continue the install. I think the original 1.5 launch isn't fully closing before launching the installer. Otherwise it goes smoothly.

I've seen it on 3 computers, 2 running Win10 and 1 running Win8. Sorry I don't have screenshots or exact error text - I can't reproduce it without reinstalling 1.5.

**Comment by Wires77** [comment]
This should be fixed going forward.  It needed to be fixed in the version you were replacing, so feel free to re-open this if you see it again when updating from 1.6 onward.
