### ISSUE TITLE
Unofficial Pandora API Discord

### ISSUE THREAD

**Issue by FireController1847** [adammhaile/Elpis#186]
Hello! 👋 

💠 I'm going around all of the Pandora Libraries's as well as their products, and telling users about a Discord server I've been making to allow us all to communicate easily and quickly. All library creators will be given their own role and their own support channel to (optionally) help users. All product creators will be given their own role, and their own support channels as well. Please join! We're looking to get as many Unofficial Pandora API dev's to come together, and allow for easy communication.

💠 Some more info about me: A simple Discord user. I'm looking to create Node.js API, but noticed there was no way to contact anyone nor a simple community behind it that I could talk to, so I've made this guild to try to make the community visible as one giant group.

💠 We think you'd be an awesome addition to the community, please, join! Let's bring this Unofficial API all into one place for easy support and documentation, as well as product listings and library listings. Hope to see you there! 👍 

[Join Here](https://discord.gg/VqzGTV8)
https://discord.gg/VqzGTV8

**Comment by FireController1847** [comment]
I've decided that this is a really bad idea. Sorry for giving you a "spam" issue.

**Comment by wokawoka** [comment]
May we know why did you change your mind? It sounded  like an excellent idea to me.

**Comment by FireController1847** [comment]
Technically, The Unofficial API is illegal. Pandora does not allow access to this, and it could bring too much attention to it which would get your product taken down.

**Comment by FireController1847** [comment]
I'm up to talk with it anytime though, you can always add me on Discord if you want.

**Comment by adammhaile** [comment]
Ha... yeah. We had a serious game of cat and mouse for a year or so while
we all used the web API. Then we reverse engineered the embedded device API
and it hasn't changed since. Fortunately they've never come after any of us
legally. You'd probably be fine.

**Comment by FireController1847** [comment]
I already deleted the server, though. I mean, I talked to some of the library debs and they refused to, you guys would be the only ones. I can remake it if you guys want me to.

**Comment by adammhaile** [comment]
Haha... Yeah, the rest are a quiet bunch

**Comment by FireController1847** [comment]
I'll only recreate it if you want me to ¯\_(ツ)_/¯
