### ISSUE TITLE
ElpisInstall_1.6.0.exe not a valid Win32 application

### ISSUE THREAD

**Issue by johnd0e** [adammhaile/Elpis#188]
Get this error trying to run installer on windows XP.
ElpisInstall_1.5.2.exe is ok

**Comment by Wires77** [comment]
Hey @johnd0e I've added a portable version to the releases page, check that out.  The installer has been upgraded to work on newer versions of Windows and will not work on Windows XP anymore.  I'll continue uploading portable versions of releases, but I can't promise they will always work on XP as I can't test them there.

**Comment by johnd0e** [comment]
Thank you. Now I'm able to run it, unfortunately it immediately crashes during "Setting up UI..."

**Comment by johnd0e** [comment]
Yes, that's the logs's end, then crash to desktop.
Please make special build with additional logging.
