### ISSUE TITLE
"This file has been tampered with and MAY BE INFECTED WITH A VIRUS!"

### ISSUE THREAD

**Issue by Pyrepenol** [adammhaile/Elpis#196]
I get this when I try to run Elpis, during the updating phase. Any ideas?

https://i.imgur.com/HM1P5rB.png

**Comment by Pyrepenol** [comment]
[09:42:33.727] Checking for updates...
[09:42:33.728] Downloading update file: https://raw.githubusercontent.com/adammhaile/Elpis/master/version.config?r=1503582153
[09:42:34.982] Info: BASS: Initialize BASS environment ...
[09:42:34.992] Info: BASS: Loading AAC Decoder

**Comment by Pyrepenol** [comment]
Fixed it! If you come across this error download [this](http://www.un4seen.com/download.php?z/2/bass_aac24) and replace the old bass_aac.dll with the packaged one.

I guess their anti-tampering code fudge the bucket for some reason. Strange that I'm the only one who had this come up, though.

**Comment by Wires77** [comment]
Certainly odd, I'm glad it worked itself out though!

**Comment by Pyrepenol** [comment]
It seems this file was automatically patched, and I had to replace that same file again. Not sure why I'm the only one who seems to have this problem...
