### ISSUE TITLE
Is there a 1.6.0 portable version?

### ISSUE THREAD

**Issue by mbrazil** [adammhaile/Elpis#197]
Is there a 1.6.0 portable version?

**Comment by mbrazil** [comment]
Ping

**Comment by Wires77** [comment]
I'll see if I can get portable build put up.

**Comment by mbrazil** [comment]
Thanks!

**Comment by seliver** [comment]
@Wires77 I made the portable versions basically by zipping the folder where Elpis is installed.

**Comment by mbrazil** [comment]
?

**Comment by Wires77** [comment]
I uploaded a portable version, but it will still end up creating and using the config file in your %AppData% directory.  For next release I hope to have a truly portable version made where the configuration file and log files are self-contained.
