### ISSUE TITLE
42 seconds of silence cycle

### ISSUE THREAD

**Issue by seliver** [adammhaile/Elpis#20]
Operating System Version?: Win 7 SP1 x64

Elpis Version?:1.4.5

Country and do you use a Proxy?:USA, no

What steps will reproduce the problem?
1. Start program
2. Play any station
3. 42 seconds of silence (though song title, etc. are listed)

What is the expected output? What do you see instead?: Music from that station; 40 seconds of silence; new "song" [title, picture] but 40 more seconds of silence. 

Please provide any additional information below.

---

I originally tried another client (ZZJ, http://ridetheclown.com/wp/saver2/) and this problem occurred after several days of use (not continuous). I let Pandora run for an hour or so and music came back. Then I tried Elpis and the music played fine for about 15 minutes. But the problem came back. Same 42 seconds of silence again. 

comment 1 
After logging out and going to bed, it came back this morning. I can only presume that it is due to the use of clients. I never had this problem with Pandora's native web app. 

comment 2
FYI: I got this problem even though i did not thumb down or skip. It may of happened from too many station changes in a short time period though.

**Comment by seliver** [comment]
PromyLOPh/pianobar#415

**Comment by BinaryBrother** [comment]
Been using Elpis for a year or so and never noticed this until now [42 seconds of silence]. I'm not sure if it's related, but this is the first time that I've seen Elpis update to a newer version immediately after a fresh download.

I was using Shuffle or "Quick Mix". Skipped like 10 times and got all 42 second silence stations. I went back and clicked another station and am listening to music, but also started Pandora in FireFox [muted] in the background so it could work out any ads, if that was the case.

*Switched back to Quick Mix and am now listening to music, fine.

*Crap, back to 42 second silence after a few songs.

*Ahh, I may have discovered something. It looks like it may be a skip-limit or something, as switching back to a regular station and not my Quick Mix resolves the issue immediately. I just tested this theory several times... My Quick Mix will not play music, most of the time, but all my other stations are fine.

**Comment by seliver** [comment]
Hmm, i personally never had this issue (although just last week started to use quick mix), but most probably it's related directly with pandora, whether it's a skip limit or something like that. But yeah, if you skip too much you will get some kind of error. 
Thanks for reporting :+1:

**Comment by BinaryBrother** [comment]
I didn't really want to post again, hence the edit on my original post, but I've heavily revised it and added some potentially useful material.

**Comment by seliver** [comment]
You did well on posting again, otherwise i wouldn't even look again :)
As i said before, this issue is not related with Elpis but with directly with Pandora, so nothing we can do for now :/
Maybe because of "maxing out" you got flagged somehow by pandora. I get too sometimes, it just happens.
PM me ;)

**Comment by agarwaldax** [comment]
@Wires77 Can we go ahead close all issues that have not been updated within this year? They can be opened as new issues if they persist.

**Comment by Wires77** [comment]
@agarwaldax Yeah, unless they have a specific fix that can be implemented, I'm fine closing them.
