### ISSUE TITLE
Debug: Caching audio data to files

### ISSUE THREAD

**Issue by a-raccoon** [adammhaile/Elpis#213]
Would it be possible to include a debugging feature which caches audio data into files, ideally with readable filenames identifying audio's metadata?

**Comment by Wires77** [comment]
We try to stay away from storing songs off into files in order to stay on Pandora's good side, so I don't think this will be possible.  What are you wanting to accomplish, maybe there is another way?

**Comment by adammhaile** [comment]
@a-raccoon As @Wires77 said, that's not possible. Technically it is, but it would be in gross violation of Pandora's Terms of Service. Elpis will not ever, in any fashion, save the audio data to files. That would be illegal.
