### ISSUE TITLE
Consider using Material Design

### ISSUE THREAD

**Issue by SoullessWaffle** [adammhaile/Elpis#22]
I'm trying not to sound like a jerk while saying this but here goes:
Currently, the app looks very 'flat' and perhaps a bit confusing to first-time users.
I believe that using [Google's Material Design spec](https://www.google.com/design/spec/material-design/introduction.html) as a guide to give the app a bit more visual depth and consistency would be a considerable improvement to user experience.

**Comment by seliver** [comment]
Hello SoullessWaffle! Thank you for your suggestion, I agree about an update to the UI, but i personally don't know nothing about material design in terms of programming and honestly, beautiful UI is not my biggest skill at all. So for that to happen, I hope someone else to contribute. But once again, thank you for your suggestion :)

**Comment by SoullessWaffle** [comment]
If I had any C# experience I would offer to contribute, but unfortunately I don't.
I did find this but I have no idea if it will be of use: http://marcangers.com/material-design-shadows-in-wpf/

**Comment by seliver** [comment]
Thanks for the tip, will have a look at it ;)

**Comment by seliver** [comment]
Marked this as postponed, for now i will not look at this in depth.
If anyone is willing to give this enhancement a try, please reply here.
Thank you.

**Comment by Wires77** [comment]
Version 1.6 has the beginnings of using Material.io with icons from that library.  I'll be looking into implementing themes, shadows, the whole shebang in version 1.7
