### ISSUE TITLE
1.4.6 Drops Global Media Key Functionality

### ISSUE THREAD

**Issue by DocBennett** [adammhaile/Elpis#24]
Updating from 1.4.5.0 to 1.4.6.0 removes the radio button option under "General" and the functial use/awareness of Global Media Keys.

![elpis1460](https://cloud.githubusercontent.com/assets/10655304/5858885/80ff2788-a224-11e4-950a-b535d5a477d7.png)
![elpis1450](https://cloud.githubusercontent.com/assets/10655304/5858886/810328ba-a224-11e4-85ef-286d7421b28f.png)

**Comment by seliver** [comment]
Hello DocBennett. Thank you for reporting this issue.
For some reason this option has been hidden on a commit made by another user, but has only been hidden the option itself, the functionality is still there. Do your Media Keys don't work with Elpis? Because here on my setup the play, pause and next buttons are recognized by Elpis and do control it.

Anyway, will change for this option to be unhidden again.

**Comment by DocBennett** [comment]
On my two computers (Windows 7) the global hotkeys stopped working entirely on 1.4.6. After uninstalled and reverting to 1.4.5 the hotkeys once again worked.

**Comment by seliver** [comment]
Have you tried the global media keys with Elpis on system tray?

--
Alexey
Em 23/01/2015 16:19, "DocBennett" <notifications@github.com> escreveu:

**Comment by Wires77** [comment]
The last set of commits before the project moved to GitHub alluded to the addition of a whole custom hotkey feature.  If that wasn't tested or removed before this release it the media keys were probably moved to that when it wasn't fully implemented.

**Comment by seliver** [comment]
It does indeed. 
Will have a try at going back to before those commits.

**Comment by seliver** [comment]
I have been inspecting the previous commits, which by the way were not made by me, and i noticed that some lines of code were commented. 
Now i can see this on the settings:
![hotkeys](https://cloud.githubusercontent.com/assets/7545867/5905724/1a71cae8-a58a-11e4-937d-46ac498772c5.JPG)
All settings are now stored on the config file and successfully loaded on application start.

**Comment by Wires77** [comment]
I'd like to re-open this issue as it still appears broken in 1.4.7

**Comment by DocBennett** [comment]
Getting the same here - 1.4.7 not responding to Global media keys. Since THIS issue was for 1.4.6 though I'll just comment on the new cards put in for 1.4.7.

**Comment by seliver** [comment]
Just published 1.4.7 again.
Please check if the issue is gone and please do what i asked you on issues #41 and #40. 
Feedback is much appreciated, thanks for contributing :+1:
