### ISSUE TITLE
1.4.6.0 Update, "Error Communicating with server"

### ISSUE THREAD

**Issue by SteelTheory** [adammhaile/Elpis#25]
After doing the 1.4.6.0 update, Elpis does not work.  It hangs for a while on the "Authenticating" login/loading screen, then gives an error message:
"Error Communicating with server"

**Comment by seliver** [comment]
Are you using proxy or is your internet failing? Because it happened to me
but the problem was related to the proxy server or the ISP.

**Comment by SteelTheory** [comment]
No proxy.  No changes to PC or network.  Only change was the update.

**Comment by seliver** [comment]
Strange. Does a reinstall solves it?

**Comment by seliver** [comment]
So does it works now?
