### ISSUE TITLE
Add Beta testing option

### ISSUE THREAD

**Issue by seliver** [adammhaile/Elpis#27]
Will add an option to receive beta updates, so that users can test the latest commits without having to compile.

**Comment by adammhaile** [comment]
Do you want to take over the update server? All it needs to be is an HTTP accessible text file. But if you update the URL in 1.4.7 then you can use it for future updates.  Actually... I could do an htaccess redirect on http://elpis.adamhaile.net/update/version.config so that you could use it now...

**Comment by seliver** [comment]
Probably it's better, yes. 
We can even store this file here at github. Can you include the file to the root of the repo?

**Comment by adammhaile** [comment]
Oh.. duh. Brilliant. Already do that with the change log. Will do that
tonight and setup the redirect.

**Comment by seliver** [comment]
Nice, thanks.
