### ISSUE TITLE
Windows Keyboard Media Keys No Longer Work

### ISSUE THREAD

**Issue by nkoszyk** [adammhaile/Elpis#28]
Using 1.4.6.0 on Windows 8.1 Update 1 (64-bit) with the Microsoft Ergonomic Keyboard 4000.

Just updated from 1.4.5 where the media keys worked. In 1.4.6, no pause/play.

**Comment by seliver** [comment]
This is the same issue as #24 and is already solved. The solution will appear in the next update shortly ;)
