### ISSUE TITLE
Show Notification on taskbar when a user liked/disliked a song through remote control

### ISSUE THREAD

**Issue by seliver** [adammhaile/Elpis#29]
Now Elpis only shows notifications when another song starts.
It might be useful to see when a song is liked or not. 
What do you think?

**Comment by SoullessWaffle** [comment]
An option to toggle this would be most welcome.

**Comment by seliver** [comment]
Ok, thank you for your opinion :+1: 
Will include this in 1.4.8 maybe.

**Comment by seliver** [comment]
This has been implemented in 64bd7e3058aee9c2bd2c8b78a558413ae2b23c34 and can already be tested on 1.4.9.
