### ISSUE TITLE
Web Remote Interface or Remote Control App for Android

### ISSUE THREAD

**Issue by seliver** [adammhaile/Elpis#3]
Hello, I was wondering if you could add a web interface for remote control of elpis. The reason, is because with a web interface I could control elpis from another room with another computer or smartphone. I think this would be quite useful. This is extremely useful in my case where I have a dedicated HTPC, and a receiver upstairs. I drive the receiver with my HTPC  and don't have to go downstairs every time I want to skip a song or pause. If not a web remote, may I suggest a remote app. Thanks for developing this great program.

**Comment by seliver** [comment]
Will start test a web interface just to be able to access it through a browser or through a simple web api. Any help is appreciated.

**Comment by seliver** [comment]
Just made the "last" commit about this matter, for now. Check the wiki for instructions.

**Comment by seliver** [comment]
To try the remote control, you can try installing the ElpisRemote on an android device, located at https://github.com/seliver/ElpisRemote .

**Comment by seliver** [comment]
Just opened this issue to ask for some feedback. 
For those who tried this feature, what do you think about it?

**Comment by briantho** [comment]
Hi, any chance you could compile an android apk for the remote, would love to test this feature. Also, do you plan on creating a web remote, in addition to the app this would be great for users who don't use android or have a ios/windows phone device, or users who would just like to use another computer for control, like me. Thanks again, and great job on this project. Glad to see it going again.

**Comment by seliver** [comment]
The version on github already has got the feature of being controlled 
within a browser on the same network, check the wiki for more info ;)
About the apk, i was thinking on putting the remote on Google Play with 
a symbolic price (a buck or something) 'cause if i create the account it 
will be solely for this purpose and it's a way of contributing, but 
haven't had the time for that yet.

**Comment by seliver** [comment]
BTW, you can get the apk at the releases section of ElpisRemote: https://github.com/seliver/ElpisRemote/releases/
Please do let your feedback after that ;)

**Comment by seliver** [comment]
I just released a new version of ElpisRemote, check it out here : https://github.com/seliver/ElpisRemote/releases/tag/1.0.1
