### ISSUE TITLE
Add Settings and Restore to Desktop to system tray functionalities

### ISSUE THREAD

**Issue by DurhamD** [adammhaile/Elpis#30]
I think it would be nice to have something like the little settings icon within the right-click menu when Elpis is minimized to system tray.
![image](https://cloud.githubusercontent.com/assets/10854728/6048690/04a87b7e-ac67-11e4-9c63-14690ae80b96.png)

Another thing that would be useful to me is a way to get Elpis back to desktop mode from minimized mode.  As it is, unless I'm missing something, I have to do this by exiting Elpis in order to run it from W7 start menu.

**Comment by seliver** [comment]
Thank you for the suggestions :)
About the the first thing, it is surely an enhancement to ponder about. What exactly has to be shown when clicked on setting there? Maybe opening Elpis with the settings page opened? Or showing some options like "Show notifications" to check/uncheck and for the others the might be a "Other Settings" button? 

About the second thing, i do not quite understand what you mean. Here on my pc, when i minimize it, i can click on the icon to show Elpis again. Could you explain what you really mean?

**Comment by DurhamD** [comment]
First thing: I think opening Elpis to the settings page would be good.Second thing: If in Settings I have not checked "Minimize  / Close to Tray", then I also can show Elpis by clicking on the icon in the task bar. However, if I have checked this option, minimizing Elpis puts into the Tray instead of the task bar.  I don't see a way to restore to desktop from the minimized-to-tray state.

Third thing (I just thought of it): When minimized to tray, it's nice to have the stations list, but it would be nicer if there were an indicator of what the currently streaming station is.  Maybe spelling it out at the top of the right-click items and-or an arrow or just an angle bracket like > Current streaming station. pointing to the current station in the station list.

 

     On Wednesday, February 4, 2015 2:19 PM, seliver <notifications@github.com> wrote:
   

 Thank you for the suggestions :)
About the the first thing, it is surely an enhancement to ponder about. What exactly has to be shown when clicked on setting there? Maybe opening Elpis with the settings page opened? Or showing some options like "Show notifications" to check/uncheck and for the others the might be a "Other Settings" button? About the second thing, i do not quite understand what you mean. Here on my pc, when i minimize it, i can click on the icon to show Elpis again. Could you explain what you really mean?—

**Comment by seliver** [comment]
> opening Elpis to the settings page

Yes, i think that is also a good idea. I'll add it to the list of things to do. Probably 1.4.8 ;)
> I don't see a way to restore to desktop from the minimized-to-tray state.

When you have Elpis on system tray, try double clicking on the icon, and it will open the Elpis window. Try it and tell something if it worked or not.
> indicator of what the currently streaming station is

I don't know how to do that, i'll have to investigate, but it is also a good idea. Maybe instead of adding a character to the station name, the best thing is to make the station bold, what do you think? 
Anyway, I'll add this to the list as well, 1.4.8 probable milestone.

Thank you for your great suggestions, DurhamD! :+1:

**Comment by DurhamD** [comment]
Yes, you're right about double-clicking the tray icon. That does open it up on the desktop.  Sorry about that.  I didn't think of that because my other tray items are single-clickers. Thanks.
Doug Durham 

     On Wednesday, February 4, 2015 3:58 PM, seliver <notifications@github.com> wrote:
   

 
opening Elpis to the settings page
Yes, i think that is also a good idea. I'll add it to the list of things to do. Probably 1.4.8 ;)
I don't see a way to restore to desktop from the minimized-to-tray state.
When you have Elpis on system tray, try double clicking on the icon, and it will open the Elpis window. Try it and tell something if it worked or not.
indicator of what the currently streaming station is
I don't know how to do that, i'll have to investigate, but it is also a good idea. Maybe instead of adding a character to the station name, the best thing is to make the station bold, what do you think? 
Anyway, I'll add this to the list as well, 1.4.8 probable milestone.Thank you for your great suggestions, DurhamD!  —

**Comment by Wires77** [comment]
There's a lot of suggestions being listed in this issue.  Some of them have been fixed already, so in the interest of cleaning up the backlog so we can focus development, I'm going to close this issue.  @DurhamD if you'd like to open a new issue (or better yet, a new pull request!) I'll take another look.
