### ISSUE TITLE
Elpis not working

### ISSUE THREAD

**Issue by dicklb** [adammhaile/Elpis#32]
I cant get Elpis to work on Windows 8.1 with Media Center (new install). Here is the error I get:

PandoraSharp.Exceptions.PandoraException: Failed to load song more than once.
Check connection and try again. ---> BassPlayer.BassStreamException: Bass Error: Unable to create stream - BASS_ERROR_UNKNOWN
   at BassPlayer.BassAudioEngine.Play(String filePath)
   at PandoraSharpPlayer.Player.PlayNextSong(Int32 retry)
   --- End of inner exception stack trace ---
   at PandoraSharpPlayer.Player.PlayNextSong(Int32 retry)
   at PandoraSharpPlayer.Player.PlayNextSong(Int32 retry)
   at PandoraSharpPlayer.Player.PlayNextSong(Int32 retry)
   at PandoraSharpPlayer.Player.PlayThread()
   at PandoraSharpPlayer.Player.<>c__DisplayClass1.<RunTask>b__0()

**Comment by seliver** [comment]
This is most probably not related to Elpis but to Pandora itself. Please try again and see if it works already.

**Comment by dicklb** [comment]
Pandora is working fine on all my devices and receivers. I have Elpis on other systems which are working fine. It still cant get it to work . . . thanx

**Comment by dicklb** [comment]
I uninstalled Elpis and then reinstalled the last version 1.4.5 and I get the same results. .

**Comment by adammhaile** [comment]
if it's broken with 1.4.5 and 1.4.6 then it's a pandora issue :(

**Comment by dicklb** [comment]
Why only this program on this system. It works in the browser. Is there any way to fix the Pandora issue?

**Comment by seliver** [comment]
It's a strange thing, indeed. Try logging out of all other devices using this account and see if it works.

**Comment by dicklb** [comment]
I have and it doesn't work. On the system I am using now Elpis works fine. If I close the program and try on the new system (with the Elpis issue) it doesn't work. I do love your program...

**Comment by seliver** [comment]
I'm glad to hear you like it :)
It's a very strange issue indeed. How about your connection, is it the same as on the other pc's?

**Comment by SoullessWaffle** [comment]
Might I suggest doing [a traceroute][1] and posting the results here?

[1]: http://help.ea.com/en/article/how-to-uo-trace/

**Comment by dicklb** [comment]
Yes. Same connection but I will try it on another Ethernet switch. . . thanx

**Comment by dicklb** [comment]
Thank you all for spending time to try to diagnose my problem. I have solved it. The issue was cleared up by moving the system in question to another Ethernet switch. Not sure why this would affect (seemingly) only Elpis as all other net connections seemed stable. All I can say is that the Ethernet switch with the issue was three switches down the line from my router. I will be making a donation to your organization this week. . . thanx again. . . Richard

**Comment by dicklb** [comment]
Thank you all for spending time to try to diagnose my problem. I have solved it. The issue was cleared up by moving the system in question to another Ethernet switch. Not sure why this would affect (seemingly) only Elpis as all other net connections seemed stable. All I can say is that the Ethernet switch with the issue was three switches down the line from my router. I will be making a donation to your organization this week. . . thanx again. . . Richard

**Comment by seliver** [comment]
I'm glad to hear that the issue was solved, Richard. I don't really have an idea of why it didn't worked on the other switch. It's beyond human logic perhaps :smile: 
And thank you if you decided to donate, help is always welcome and needed :+1:
