### ISSUE TITLE
Elpis error - BASS_ERROR_TIMEOUT

### ISSUE THREAD

**Issue by shankstar** [adammhaile/Elpis#34]
hello everyone,

Elpis has wored flawless since i heard about it from searching for a sidebar or gadget and until recently it stopped working and can't figure out what this error means.

PandoraSharp.Exceptions.PandoraException: Failed to load song more than once.
Check connection and try again. ---> BassPlayer.BassStreamException: Bass Error: Unable to create stream - BASS_ERROR_TIMEOUT
   at BassPlayer.BassAudioEngine.Play(String filePath)
   at PandoraSharpPlayer.Player.PlayNextSong(Int32 retry)
   --- End of inner exception stack trace ---
   at PandoraSharpPlayer.Player.PlayNextSong(Int32 retry)
   at PandoraSharpPlayer.Player.PlayNextSong(Int32 retry)
   at PandoraSharpPlayer.Player.PlayNextSong(Int32 retry)
   at PandoraSharpPlayer.Player.PlayThread()
   at PandoraSharpPlayer.Player.<>c__DisplayClass1.<RunTask>b__0()

**Comment by seliver** [comment]
Hello shankstar. 
By the look of it, looks like the skip limit was reached, because here on my machine it is happening the exact same thing when i skip too much.
Can you please specify what is your setup (Windows, proxy, vpn).
I will also change the title as the one now says nothing about there's an error.

**Comment by shankstar** [comment]
Windows 7 64bit the error happens when i select a station to listen to and then the error i have gotten Elpis to play the song but no sound.

**Comment by seliver** [comment]
Yep, it is probable to be related to many skips/channel jumps. No can do 
about that :(
This error of Elpis playing but no sound is, for what i could see, 
affecting all unnofficial clients (Pithos, pianobar, etc), and must be 
probably a Pandora restriction of some kind, unfortuntelly :(

**Comment by seliver** [comment]
Anyway, give it some time. Tomorrow is highly probable to work again :) 
Say something tomorrow if it works or not. Thanks!

**Comment by shankstar** [comment]
alright thanks for the help will try again hopfully it works.

**Comment by seliver** [comment]
;)

**Comment by seliver** [comment]
So, did it worked?

**Comment by xytrix** [comment]
I experienced this issue recently. Assuming it was related to Pandora blocking my account temporarily I took no action other than to wait. Came back weeks later, still had the problem. Decided to try rebooting my computer. Problem fixed. Hopefully that'll help someone in the future, I see this issue has a few duplicates.
