### ISSUE TITLE
Skip Limit Reached possible workaround

### ISSUE THREAD

**Issue by seliver** [adammhaile/Elpis#35]
Hello all!
While listening to Elpis, for some reason i reached the skip limit without even having skipped a single time, just disliking one or two song (2 at most).
When music stopped i saw that the error was "Skip limit reached". I said "dang it!" and pressed the skip button or play button (don't know for sure) and magically music started to play. WOW! 
After a while, music stopped again and the same method worked (not the "dang" word, but the button pressing stuff :smile: )
So i wanted to ask you to test it and see if it works to you. If it does, i will have to investigate what's the matter inside the Elpis engine or find a technical workaround for this.
Edit: just after writing this, that error appeared. Clicked on Skip and music started playing. Hmm.

**Comment by ChikNoods** [comment]
I just installed the new version and without playing one song I get skip limit reached and nothing happens

**Comment by benjaminmetzler** [comment]
I am seeing this problem on a regular basis.  I have to go back out the station list and then back in.  I am running Windows 7 and Elpis 1.5.  The problem seemed to appear in the last month or so.  I do not generally skip (maybe once a week) or thumbs down songs (almost never).

**Comment by seliver** [comment]
As already discussed on other threads and even on other pandora clients, this issue is caused by pandora itself. So there's nothing to be done on Elpis. When I posted this issue, I was just having luck with the procedure I described.
