### ISSUE TITLE
Media keys not working in 1.4.6

### ISSUE THREAD

**Issue by mattkolb** [adammhaile/Elpis#36]
The automatic update prompt came up to go from 1.4.5 to 1.4.6. I went through the upgrade process. It had an error the next time I started Elpis (now I wish I had written it down). I didn't pay much attention because I just closed it and opened it again without much issue. However, the media keys on my keyboard weren't working. I uninstalled and reinstalled 1.4.6 with the same result. I uninstalled 1.4.6 and installed 1.4.5 again. The media keys are back to normal.

If I can give you any debug info, don't hesitate to ask.

**Comment by Wires77** [comment]
See #24 , there's already a fix in

**Comment by seliver** [comment]
Will include the fix in 1.4.7 soon.
Thanks for reporting :)
