### ISSUE TITLE
Elpis 1.4.7 crashes when setting certain hotkeys

### ISSUE THREAD

**Issue by Wires77** [adammhaile/Elpis#38]
Open the hotkey screen and add a new hotkey with the global setting unchecked.  In the hotkey box, type a letter to see the crash.

**Comment by seliver** [comment]
Interesting.

**Comment by seliver** [comment]
This is caused by an uncatched exception. Here's the message: "Alphanumeric Keys without modifiers are not supported as hotkeys"

**Comment by seliver** [comment]
I think it is solved now.
