### ISSUE TITLE
Elpis 1.4.7 takes control of the spacebar

### ISSUE THREAD

**Issue by Wires77** [adammhaile/Elpis#39]
While Elpis is open and the spacebar is a global hotkey the spacebar works in no other program.  I believe this is related to the play/pause hotkey defaulting to the spacebar.  This bug appears to be in effect for any key that is set to global.

**Comment by seliver** [comment]
I don't know if this can be considered a bug because as it is now done, if a hotkey is global, Elpis consumes it and does not transmits it further.

**Comment by Wires77** [comment]
While I understand, maybe either make a warning on the UI or disable setting the spacebar as a global hotkey much like the unmodified letters are right now.

**Comment by seliver** [comment]
I see what you mean, i did set the spacebar and it did not worked in any other program. Will find a way to relaunch the command.

**Comment by seliver** [comment]
After a little research and some thought, i realized that it doesn't make sense to have other apps to respond to the same hotkey. What's the purpose of that anyway?
It will stay like this until someone finds a workaround as i haven't found any.
