### ISSUE TITLE
Elpis 1.4.7 Not responding to or recording global media hotkeys

### ISSUE THREAD

**Issue by DocBennett** [adammhaile/Elpis#41]
The newest update, like v1.4.6, will not respond to global hotkey input by default. It also is not recording the keystroke of the keys when trying to assign them to existing functions in the new "Global Hotkeys" section of the settings interface.

**Comment by seliver** [comment]
will not respond to global hotkey input by default
You mean the ones set by default when you first start Elpis 1.4.7?

    not recording the keystroke of the keys when trying to assign them to existing functions
Well, for some reason they work on my machine.

**Comment by DocBennett** [comment]
The given "default" media keys do work, focused or globally. I'm reporting for 1.4.7 the same issue as in Issue #24 . Using a keyboard's play/pause, back/next track buttons aren't being recognized for me at all on two different Windows 7 64 bit systems.

**Comment by seliver** [comment]
But have you checked if your keyboard buttons are the same as of the ones mapped in Elpis by default?

**Comment by DocBennett** [comment]
The Elpis default mappings are just typical keyboard keys that I use all the time. The unique play/pase/next/back buttons are not being read when I try to set them as the new hotkeys.

**Comment by seliver** [comment]
Have you erased the old ones?

**Comment by DocBennett** [comment]
I have tried the latest 1.4.7 install. I cleared out all of the default hotkeys. 

Then - when I go to log the new ones, it won't take JUST the MediaPlayPause or MediaNextTrack etc. w/out a modifyer. All get captured OK with a shift or alt or ctrl added, but not alone.

[Example here](http://i.imgur.com/FZTnO1g.png)

**Comment by seliver** [comment]
I'm sorry but i have to close one of the issues so that we don't have 2 equal issues. Now the discussion continues on #40.
