### ISSUE TITLE
Elpis 1.4.5 does not update to 1.4.7

### ISSUE THREAD

**Issue by Wires77** [adammhaile/Elpis#42]
Instead of updating to the latest version, it tries to update to 1.4.6 still:

![2015-03-04 10_30_42-elpis](https://cloud.githubusercontent.com/assets/1209372/6489178/9151cffa-c259-11e4-9894-048de1a1d07e.png)

**Comment by seliver** [comment]
That's because i didn't open the update port for 1.4.7 as of yet. It got delayed because of the last-hour issues.

**Comment by seliver** [comment]
As for now, will remove the 1.4.7 release to correct the hotkeys bugs.
