### ISSUE TITLE
No Control Black Window

### ISSUE THREAD

**Issue by gitfreestone** [adammhaile/Elpis#45]
When my Elpis auto upgraded (and even a uninstall re-install) I no longer see the black window that shows artwork and allows me to control pause, like etc.  I am using latest windows 8.1.  If I right click I get a pop up but when I select Elpis I still dont see the window.  If I hover I see this 
![elpis](https://cloud.githubusercontent.com/assets/11586600/6765555/a9d9a10e-cfb2-11e4-82ab-6c38aa24df82.png)

Thanks....love this tool.  so much better than having the browser tied up streaming.

**Comment by seliver** [comment]
Just to complete this issue, gitfreestone mentioned on facebook that he used an external usb monitor, right?

**Comment by gitfreestone** [comment]
I had Elpis on an external USB monitor attached to my laptop I then left my house to travel and now do not have the monitor attached.  It is the only thing I can think of that changed other than the update to the newest version of Elpis.  I really would not expect the monitor to be an issue since windows should just reassign the display to the  only monitor I am now using.  I was just wondering if you do anything that would keep it assigned to a monitor that is no longer attached but as long as you are not doing anything like that I doubt the issue is related to that ?  Perhaps a conflict with some other program I am running ?  I could likely hook another monitor up on the USB connection if you want me to?

**Comment by gitfreestone** [comment]
I should mention that Elpis is still playing and I can control it via the icon in the pop up background process.  Funny I dont know what windows calls that area of the tray but if I go there and then right click I can control the play, like forward etc.

**Comment by seliver** [comment]
Hmm, strange.

Try this: quit Elpis, go to **C:\Users\<USERNAME>\AppData\Roaming\Elpis** and open the **elpis.config** file. In that file delete the lines **Elpis_StartupLocation** and **Elpis_StartupSize** and save the file. 
After that run Elpis again and see if this solved the issue.

**Comment by gitfreestone** [comment]
Great…..that fixed the issue and the new entries are

 

Elpis_StartupLocation|-1,-1

Elpis_StartupSize|0,0

 

So it was positioned to invisible coordinates that the USB monitor was on.  Dang thought I was reaching on that one.

 

Thanks for the fix.   Much easier to pause when I get a phone call now.

 

John Williams

Freestone Products, Ltd

Cell: 720-560-1460

Office: 303-699-9299

**Comment by seliver** [comment]
Glad it helped :)
