### ISSUE TITLE
Installation problem Windows XP

### ISSUE THREAD

**Issue by 850i** [adammhaile/Elpis#46]
When I am trying to install Elpis on Windows XP the installer complains: "The installer was interrupted before Elpis could be installed. You need to restart the installer to try again". Trying again obviously doesn't help.

I unpacked the installer and ran MSI installation directly
>> msiexec.exe /i ElpisSetup.msi /log setup.log

Below is the contents of the log

=== Logging started: 3/22/2015  16:50:49 ===
Action 16:50:49: INSTALL. 
Action start 16:50:49: INSTALL.
Action 16:50:49: DIRCA_CheckFX. 
Action start 16:50:49: DIRCA_CheckFX.
Action ended 16:50:49: DIRCA_CheckFX. Return value 3.
Action 16:50:49: FatalErrorForm. 
Action start 16:50:49: FatalErrorForm.
Info 2898. VSI_MS_Sans_Serif13.0_0_0, MS Sans Serif, 0
DEBUG: Error 2826:  Control Line1 on dialog FatalErrorForm extends beyond the boundaries of the dialog to the right by 3 pixels
The installer has encountered an unexpected error installing this package. This may indicate a problem with this package. The error code is 2826. The arguments are: FatalErrorForm, Line1, to the right
DEBUG: Error 2826:  Control Line2 on dialog FatalErrorForm extends beyond the boundaries of the dialog to the right by 3 pixels
The installer has encountered an unexpected error installing this package. This may indicate a problem with this package. The error code is 2826. The arguments are: FatalErrorForm, Line2, to the right
DEBUG: Error 2826:  Control BannerBmp on dialog FatalErrorForm extends beyond the boundaries of the dialog to the right by 3 pixels
The installer has encountered an unexpected error installing this package. This may indicate a problem with this package. The error code is 2826. The arguments are: FatalErrorForm, BannerBmp, to the right
Info 2898. VsdDefaultUIFont.524F4245_5254_5341_4C45_534153783400, MS Sans Serif, 0
Info 2898. VSI_MS_Sans_Serif16.0_1_0, MS Sans Serif, 0
Action 16:50:49: FatalErrorForm. Dialog created
Action ended 16:50:52: FatalErrorForm. Return value 1.
Action ended 16:50:52: INSTALL. Return value 3.
Property(C): UpgradeCode = {F0962B86-5C6F-4A2C-98F4-2FF9D0AC46AD}
Property(C): ProgramMenuFolder = H:\Documents and Settings\user\Start Menu\Programs\
Property(C): SourceDir = H:\Extrct\
Property(C): DesktopFolder = H:\Documents and Settings\user\Desktop\
Property(C): VSDFrameworkVersion = v4.0
Property(C): VSDFrameworkProfile = Client
Property(C): VSDAllowLaterFrameworkVersions = False
Property(C): ProductName = Elpis
Property(C): ProductCode = {A8802592-5D0C-4431-A159-DC5F11FB9D96}
Property(C): ProductVersion = 1.4.6
Property(C): Manufacturer = Adam Haile
Property(C): ARPCONTACT = Adam Haile
Property(C): ARPCOMMENTS = Elpis Pandora Client Installer
Property(C): ARPURLINFOABOUT = http://elpis.adamhaile.net
Property(C): ProductLanguage = 1033
Property(C): ARPPRODUCTICON = _853F67D554F05449430E7E.exe
Property(C): SecureCustomProperties = PREVIOUSVERSIONSINSTALLED;NEWERPRODUCTFOUND
Property(C): RedirectedDllSupport = 2
Property(C): VersionNT = 501
Property(C): VSDNETURLMSG = This setup requires the .NET Framework version [1].  Please install the .NET Framework and run this setup again.  The .NET Framework can be obtained from the web.  Would you like to do this now?
Property(C): VSDIISMSG = This setup requires Internet Information Server 5.1 or higher and Windows XP or higher.  This setup cannot be installed on Windows 2000.  Please install Internet Information Server or a newer operating system and run this setup again.
Property(C): VSDUIANDADVERTISED = This advertised application will not be installed because it might be unsafe. Contact your administrator to change the installation user interface option of the package to basic.
Property(C): VSDNETMSG = This setup requires the .NET Framework version [1].  Please install the .NET Framework and run this setup again.
Property(C): VSDINVALIDURLMSG = The specified path '[2]' is unavailable. The Internet Information Server might not be running or the path exists and is redirected to another machine. Please check the status of this virtual directory in the Internet Services Manager.
Property(C): VSDVERSIONMSG = Unable to install because a newer version of this product is already installed.
Property(C): DefaultUIFont = VsdDefaultUIFont.524F4245_5254_5341_4C45_534153783400
Property(C): MaintenanceForm_Action = Repair
Property(C): FolderForm_AllUsers = ME
Property(C): FolderForm_AllUsersVisible = 1
Property(C): ErrorDialog = ErrorDialog
Property(C): SFF_UpFldrBtn = UpFldrBtn
Property(C): SFF_NewFldrBtn = NewFldrBtn
Property(C): AdminMaintenanceForm_Action = Repair
Property(C): WelcomeForm_NextArgs = ReadmeForm
Property(C): ReadmeForm_PrevArgs = WelcomeForm
Property(C): ReadmeForm_NextArgs = FolderForm
Property(C): FolderForm_PrevArgs = ReadmeForm
Property(C): FolderForm_NextArgs = ConfirmInstallForm
Property(C): ConfirmInstallForm_PrevArgs = FolderForm
Property(C): AdminWelcomeForm_NextArgs = AdminFolderForm
Property(C): AdminFolderForm_PrevArgs = AdminWelcomeForm
Property(C): AdminFolderForm_NextArgs = AdminConfirmInstallForm
Property(C): AdminConfirmInstallForm_PrevArgs = AdminFolderForm
Property(C): LAUNCHAPP = 1
Property(C): PackageCode = {512001F7-419A-49C2-A1AD-ADFBAFFFD32F}
Property(C): ProductState = -1
Property(C): PackagecodeChanging = 1
Property(C): CURRENTDIRECTORY = H:\Extrct
Property(C): CLIENTUILEVEL = 0
Property(C): CLIENTPROCESSID = 2928
Property(C): VersionDatabase = 200
Property(C): VersionMsi = 3.01
Property(C): WindowsBuild = 2600
Property(C): ServicePackLevel = 3
Property(C): ServicePackLevelMinor = 0
Property(C): MsiNTProductType = 1
Property(C): WindowsFolder = H:\WINDOWS\
Property(C): WindowsVolume = H:\
Property(C): SystemFolder = H:\WINDOWS\system32\
Property(C): System16Folder = H:\WINDOWS\system\
Property(C): RemoteAdminTS = 1
Property(C): TempFolder = H:\DOCUME~1\user\LOCALS~1\Temp\
Property(C): ProgramFilesFolder = H:\Program Files\
Property(C): CommonFilesFolder = H:\Program Files\Common Files\
Property(C): AppDataFolder = H:\Documents and Settings\user\Application Data\
Property(C): FavoritesFolder = H:\Documents and Settings\user\Favorites\
Property(C): NetHoodFolder = H:\Documents and Settings\user\NetHood\
Property(C): PersonalFolder = H:\Documents and Settings\user\My Documents\
Property(C): PrintHoodFolder = H:\Documents and Settings\user\PrintHood\
Property(C): RecentFolder = H:\Documents and Settings\user\Recent\
Property(C): SendToFolder = H:\Documents and Settings\user\SendTo\
Property(C): TemplateFolder = H:\Documents and Settings\user\Templates\
Property(C): CommonAppDataFolder = H:\Documents and Settings\All Users\Application Data\
Property(C): LocalAppDataFolder = H:\Documents and Settings\user\Local Settings\Application Data\
Property(C): MyPicturesFolder = H:\Documents and Settings\user\My Documents\My Pictures\
Property(C): AdminToolsFolder = H:\Documents and Settings\user\Start Menu\Programs\Administrative Tools\
Property(C): StartupFolder = H:\Documents and Settings\user\Start Menu\Programs\Startup\
Property(C): StartMenuFolder = H:\Documents and Settings\user\Start Menu\
Property(C): FontsFolder = H:\WINDOWS\Fonts\
Property(C): GPTSupport = 1
Property(C): OLEAdvtSupport = 1
Property(C): ShellAdvtSupport = 1
Property(C): Intel = 6
Property(C): PhysicalMemory = 3519
Property(C): VirtualMemory = 5162
Property(C): AdminUser = 1
Property(C): LogonUser = user
Property(C): UserLanguageID = 1033
Property(C): ComputerName = MOB
Property(C): SystemLanguageID = 1033
Property(C): ScreenX = 1024
Property(C): ScreenY = 768
Property(C): CaptionHeight = 26
Property(C): BorderTop = 1
Property(C): BorderSide = 1
Property(C): TextHeight = 16
Property(C): ColorBits = 16
Property(C): TTCSupport = 1
Property(C): Time = 16:50:52
Property(C): Date = 3/22/2015
Property(C): MsiNetAssemblySupport = 4.0.30319.1
Property(C): MsiWin32AssemblySupport = 5.1.2600.5512
Property(C): Privileged = 1
Property(C): USERNAME = mob
Property(C): DATABASE = H:\DOCUME~1\user\LOCALS~1\Temp\14f79d.msi
Property(C): OriginalDatabase = H:\Extrct\ElpisSetup.msi
Property(C): SOURCEDIR = H:\Extrct\
Property(C): VersionHandler = 3.01
Property(C): UILevel = 5
Property(C): ACTION = INSTALL
Property(C): EXECUTEACTION = INSTALL
=== Logging stopped: 3/22/2015  16:50:52 ===
MSI (c) (70:F4) [16:50:52:125]: Product: Elpis -- Installation failed.

**Comment by seliver** [comment]
Try installing http://www.microsoft.com/en-US/download/details.aspx?id=17851 , restart the pc and then try installing Elpis again.

**Comment by A-Better-User** [comment]
Find and download Orca. Use it to open up the msi file and look for two Actions. "DIRCA_CheckFx" and "VSDCA_VsdLaunchConditions". Delete them. You'll find them in tables InstallExecuteSequence and InstallUISequence. They're also in the CustomAction table, but I've found deleting them in just the execution sequence tables sufficed.

I don't know why it crashes on XP only, but I believe it's because XP doesn't have MSVBDPCA.dll. You can find more information on the Actions I mentioned here: http://stackoverflow.com/a/8613979

+1 for building something related to Pandora!

**Comment by rasputino** [comment]
Thank you A-Better-User!

**Comment by A-Better-User** [comment]
Just wanted to stop by and say if (in the future) you have any troubles using this modified msi on Windows 7 I'd recommend figuring out and learning to use WiX to write your own installers. My modified msi stopped working for some reason and now I have to maintain 2 separate installers for XP and Win7. So I'm just gonna learn WiX when I have time and work with that.

**Comment by seliver** [comment]
The thing is that XP is now discontinued by Microsoft.

**Comment by phatpaul** [comment]
I know that Win XP is no longer supported by M$ (they love to remind me).  

But are you saying that Elpis is no longer supported in Win XP?  It says that it is supported in the description here.

I was about to give up on updating this program until I found this thread.  I suspect most people won't bother to search as much as I did.

BTW, I don't plan on or see any reason to upgrade this machine from XP.  But now it is near impossible to keep Elpis up to date.

**Comment by seliver** [comment]
I'm not saying that. What I am saying is that any further releases will just not be tested on Windows XP and if an issue is found in Elpis only because of it being used in XP will most probably not be solved. But as far as I am aware, v1.5.0 is a working release even on XP. Have you tried it?

**Comment by 850i** [comment]
I am going to try in couple of weeks.
