### ISSUE TITLE
PandoraSharp.Exceptions.PandoraException: Failed to load song more than once.

### ISSUE THREAD

**Issue by Inphamuz-Iconoclast** [adammhaile/Elpis#47]
Three days ago, Elpis 1.4.7.0 began notifying me of an error and not playing music. When elpis loads, it displays "Loading Station List" and the white bar rotates.
It stops, then displays the Stations and above it, an orange triangle with an exclamation point in it (!). When I click it it says "All Hope Is Lost, The Box Is Open!" and below that it says in red text "Failed to load song more than once".
"Check connection and try again." and that has a button under it that reads "Show Error Detail" which provides the following: 

PandoraSharp.Exceptions.PandoraException: Failed to load song more than once.
Check connection and try again. ---> BassPlayer.BassStreamException: Bass Error: Unable to create stream - BASS_ERROR_FILEOPEN
   at BassPlayer.BassAudioEngine.Play(String filePath)
   at PandoraSharpPlayer.Player.PlayNextSong(Int32 retry)
   --- End of inner exception stack trace ---
   at PandoraSharpPlayer.Player.PlayNextSong(Int32 retry)
   at PandoraSharpPlayer.Player.PlayNextSong(Int32 retry)
   at PandoraSharpPlayer.Player.PlayNextSong(Int32 retry)
   at PandoraSharpPlayer.Player.PlayThread()
   at PandoraSharpPlayer.Player.<>c__DisplayClass1.<RunTask>b__0()

I have tried the following:

1. Obtain a new IP address.
2. Flush DNS
3. Release and Renew IP address
4. Logged into Pandora via two computers through Firefox and Chrome and it works without any issues or error messages at all
5. I have tried rebooting the computer
6. I have toggled audio format from AAC plus to MP3 and back again with no noticeable changes
7.  I have checked and unchecked the box for "Automatically play last station"
8. I have enabled Scroggler

No matter what I do, the error persists.

**Comment by seliver** [comment]
When was the last time Elpis player music? Have you tried with another 
account?
Have you tried using Elpis on another PC with the same account?

Alexey

**Comment by Inphamuz-Iconoclast** [comment]
Thank you for your prompt response seliver, I appreciate it very much.

The last time it played music was about 3-4 days ago.

It seems to be a problem with Pandora itself, more specifically, my account.

The reason I say that is because if I visit Pandora.com it all loads fine, and will even play music if I type something random in the box, WITHOUT LOGGING IN.

As soon as I log in, I receive this error message: 
"We've encountered an error. Sorry, it's our fault. Please click 'reload' to continue listening. Reload"

Apparently it seems my account has been flagged for some reason, unknown to me. I have searched emails to see if they have sent me any type of notification.

While logged into my Pandora account, I DID notice SOMETHING.. maybe it's nothing important or related to this but it only had ONE option for Audio Quality, but did not give an exact value, only "Regular Audio" and Pandora One high quality Audio..

The reason I mention that is because I had been toggling these settings in Elpis, when it was working fine.. hopefully I didn't screw myself.. I did NOT ever select the highest quality, only AAC and MP3.

**Comment by seliver** [comment]
I wouldn't worry much if I were you. Usually if you leave your account alone for a day or two, the flagging will be lifted. That is if you are using free Pandora, otherwise I think contacting Pandora is not a bad idea :)

**Comment by Inphamuz-Iconoclast** [comment]
Thank you, I will wait a few days and give it a try again. I use the free one :)

**Comment by seliver** [comment]
Or you can always use another one :)

Alexey
