### ISSUE TITLE
Write song playing to file?

### ISSUE THREAD

**Issue by MC42** [adammhaile/Elpis#48]
Hi.  I really do enjoy using Elpis, and play music through it frequently.  I do livestreaming sometimes, and one of the requirements is proper attribution of music.  My streaming software supports window capture, but Elpis doesn't format properly during my streams.  Would it be possible to have a file path option where the title of the song, album name, and artist are pushed to?  Thanks in advance.

**Comment by seliver** [comment]
Hi. Can you please explain a little better what you need?

**Comment by MC42** [comment]
I use Open Broadcasting Software for streaming, and it has an option to display (on stream) a text file. Other streaming softwares have modules for writing to file, but OBS doesn't. If the title of the song, and artist could be written to file when the song begins to play, that'd be exactly what I need. So, In short, writing the song info to a text file is all I'd need. For example:

A file path of x:/song.txt with the format $song - $artist would be imported as a text file into OBS with the format of the text file. 

-----Original Message-----

**Comment by seliver** [comment]
I see. 
It's a very specific and personal feature request, and as I am not seeing the usefulness of it for me, I will not implement this, unless many will ask for it to happen. 
On the other hand, You can do it and make a pull request after that, if you want. 
But in the meanwhile, it's a no.

**Comment by MC42** [comment]
Allright, fair enough.  Thank you for a straight answer.  Best of luck!
