### ISSUE TITLE
Elpis fails to load next song, plays commercial instead.

### ISSUE THREAD

**Issue by seliver** [adammhaile/Elpis#5]
**Operating System Version?:** Windows 7

**Elpis Version?:** 1.4.5.0

**Country and do you use a Proxy?:** USA, no proxy

**What steps will reproduce the problem?**
1. Start Elpis; it plays 1-2 songs without problem, then fails to load the next. It does get title info for the next song, but it never starts playing.
2. Restart Elpis. The station loads a song, with title info and album art, but instead of playing the song, it plays a commercial. Next song fails to load.
3. Restart Elpis again, spinning wait icon, song takes 5+ minutes to load.

Starting yesterday (1/31), I could not load more than 1 song at a time with Elpis. Starting today (2/1) I have gotten this behavior twice now. I'm going to reinstall Elpis, but I assume the problem is a change in the Pandora webservice.

The attached log is the run where I got the commercial instead of music.

Let me know if there's anything else I can provide. I love Elpis and would be sad to lose it!
Log files:
https://gist.github.com/seliver/3c4bce3e4367e6fb6c14
https://gist.github.com/seliver/1c99312b36f07627f05c

[Edit]

As an update, I've been experiencing this with high frequency on 3 different computers (Windows 7, 8), After it happens, I typically go back to listening on the website for a while, and Elpis will work again sometime later.

**Comment by seliver** [comment]
Never happened to me. Can't verify this.

**Comment by seliver** [comment]
Just happened this to me.

**Comment by Wires77** [comment]
This has been happening to me today.  Not sure if it's on Pandora's end or Elpis', but about every other song is either a commercial or fails to load.

**Comment by seliver** [comment]
Yep, happened to me aswell. Have been investigating, found nothing 
suspicious with the streaming links which come from the API calls. 
Probably Pandora is forcing commercials for non-official clients.

Alexey

**Comment by adammhaile** [comment]
I looked into this a while back and made Elpis download all the tracks so I
could confirm my suspicion... and yup, they embed the ad right in the music
track. Sometimes at the beginning, sometimes at the end. Still not sure how
they know it's Elpis exactly but they are definitely targeting it (and
pianobar, pithos, etc) directly.

**Comment by Wires77** [comment]
Maybe they have some key that distinguishes between internal API calls and API calls from something like PandoraSharp

**Comment by agarwaldax** [comment]
Is this still an issue or can we go ahead and close it?
