### ISSUE TITLE
"Tried of this song" option on system tray right-click

### ISSUE THREAD

**Issue by pgorbas** [adammhaile/Elpis#52]
Pandora has a tendency to repeat and re-repeat the same set of songs all the time.

Pandora has a "sleep this song for one month" or "Tired of this song" feature.

Please support this feature - I have no idea how to do so myself.

**Comment by seliver** [comment]
It is already implemented.
Check this image : 
http://core4.staticworld.net/images/article/2013/02/elpis-01-580-100024617-large.jpg

Alexey

**Comment by pgorbas** [comment]
I see the confusion - you pulled up that option from the main interface 'song menu', whereas I almost exclusively use the right click menu from the task bar icon - please see screen shot.  The task Icon menu does not have the 'Song Menu' or the 'Tired of this song' options...

![capture](https://cloud.githubusercontent.com/assets/11726837/8021189/02504c2c-0c5b-11e5-9ac4-f383afcd1a64.JPG)

Please reopen issue and consider implementing the features on the right click  context menu.

**Comment by seliver** [comment]
I see what you need :)

**Comment by seliver** [comment]
This is now implemented in beta version 1.4.12. Check it out!

**Comment by pgorbas** [comment]
Looks Good! thank you.
