### ISSUE TITLE
Feature Request: Audio Output Device

### ISSUE THREAD

**Issue by thantik** [adammhaile/Elpis#53]
I regularly use my desktop machine to play whole-house audio, but I also play games on my headphones.

Could there be some options for which audio output device that Elpis uses, so that I can direct output to my house, instead of the default audio device?

**Comment by seliver** [comment]
That is a good idea indeed, but have no clue of how one implements this.

2015-05-05 17:50 GMT+01:00 thantik <notifications@github.com>:

**Comment by joecoolio** [comment]
I'm totally new to this app, but I also have been looking for such a feature for a long time.

I just took a peek at the code, but it appears that the Bass engine being used for output already handles switching between devices:  http://www.un4seen.com/doc/#bass/BASS_SetDevice.html

You call BOOL BASS_Init() with a device number that you get from BASS_GetDeviceInfo().  Then after whatever device is init'd, you select it and then open the stream.
BASS_SetDevice(2); // select device 2
stream=BASS_StreamCreateFile(FALSE, "afile.mp3", 0, 0, 0); // create the stream

After digging through BassPlayer.cs, it appears that all that stuff is already handled if you change this line in LoadSettings() to pull from a config file (or a UI element):
 _SoundDevice = "Default Sound Device";

**Comment by seliver** [comment]
Will have to dig in but for now I'm short in time.

Alexey

**Comment by joecoolio** [comment]
I spent some time and got this working.  I can't commit, so the zip file with my changes is [here](https://drive.google.com/file/d/0B3ppxPxMzdhDS1ZTdkNScEJHQUU/view?usp=sharing).

I added a new dropdown on the settings page that enumerates the devices in the system.  When you pick a new one and save, it'll switch to that device.  Currently playing streams will switch as soon you push the save button.

**Comment by seliver** [comment]
Great! Let's see how it works :)
If you can, please make a pull requests. This way it is much easier to 
see what you changed and merge these changes to the project. For that 
you need first to make a fork of the project, commit those changes to 
this fork and create a pull request here on Elpis.
If you can't do that, i'll try to merge the files by myself.

Alexey

**Comment by joecoolio** [comment]
Will do.  I'll get that done shortly.

**Comment by seliver** [comment]
Great! thanks

Alexey

**Comment by seliver** [comment]
This enhancement is now launched as a beta update and will be included in the next stable release, if everything goes fine. Thanks @joecoolio !

**Comment by ickyspot** [comment]
hi why is elpis broken ?????

**Comment by adammhaile** [comment]
Could you send text or screenshot of the error you are getting?
It is working fine here, so we'll need more details.

**Comment by seliver** [comment]
Will close this and consider this solved.

**Comment by DocBennett** [comment]
Should this feature take into account paired bluetooth speakers or is it only going to find the soundcard & USB outputs? 

I have a Samsung Airplay audio bar in my office connected via bluetooth. I only have four options, my USB headset (Arches) and three from the Realtek onboard sound card. ![My Options](http://i.imgur.com/6MwXyLu.png)

If this isn't within the scope of this issue I will submit a new one specific to Bluetooth playback I suppose.

**Comment by seliver** [comment]
Yes, please submit a new issue. Thanks!

----- Mensagem Original -----
De: "Doc Bennett" <notifications@github.com>
Enviado: ‎20/‎08/‎2015 20:01
Para: "adammhaile/Elpis" <Elpis@noreply.github.com>
Cc: "seliver" <alexeyseliverstov.dev@gmail.com>
Assunto: Re: [Elpis] Feature Request: Audio Output Device (#53)

Should this feature take into account paired bluetooth speakers or is it only going to find the soundcard & USB outputs? 
I have a Samsung Airplay audio bar in my office connected via bluetooth. I only have four options, my USB headset (Arches) and three from the Realtek onboard sound card. 
If this isn't within the scope of this issue I will submit a new one specific to Bluetooth playback I suppose.
