### ISSUE TITLE
No Main UI display.

### ISSUE THREAD

**Issue by wyzerd** [adammhaile/Elpis#54]
I just installed 1.49. It shows in the taskbar as well as the notification section. Right clicking the notification allows station selection and all the features associated with the notification icon, but the main application will not show up on the desktop. Mouseover displays a blank transparent window. Mouseclick does nothing. 

OS Windows 7 Pro x64 SP1. 
4GB Mem
2.66 Core2 Duo

**Comment by wyzerd** [comment]
I found out what causes the issue.
steps to duplicate.
On a system with 2 Monitors:
1. set display number #2 (to the right of #1) to be the primary display.
2. Open Elpis, observe you cannot see the main UI. 
3. Close Elpis
4. Set Primary back to Display #1 
5. Start Elpis and notice it is on the far right of #2 above where the taskbar used to be.

At this point I would not call it "closed" but something of a minor bug with a good workaround and of low priority (even though I am sure it is an easy fix).

**Comment by seliver** [comment]
Will see what can be done about it.

Alexey

**Comment by wyzerd** [comment]
I had to do something similar at work. Here is the code I used:
    window.moveTo screen.availWidth-GUIWidth, 0
    window.resizeTo GUIWidth,screen.availHeight

But my app takes the entire height so you would also want a variable for where I used 0 and screen.availHeight.
