### ISSUE TITLE
Installation instructions

### ISSUE THREAD

**Issue by zrtech** [adammhaile/Elpis#55]
Downloaded this on Windows 7. Cannot find any install, setup, executable or msi files to run. How do I install this application??

**Comment by seliver** [comment]
What exactly have you downloaded?
To download the installer, go here
https://github.com/adammhaile/Elpis/releases and download the version you
want (latest stable is the green one). Make sure you download the .exe
file. After downloading you just execute that file to install Elpis.
Em 16/05/2015 00:33, "Zahir Narsisto Rodulfo" <notifications@github.com>
escreveu:

**Comment by zrtech** [comment]
I see now. I didn't know how to navigate to the release page you provided me. Thank you for direct linking me. Works great. Gave the project a shout out on my company's page. http://www.zrtechnologies.com/content/free-pandora-desktop-app

**Comment by seliver** [comment]
Thanks! Glad i helped!
