### ISSUE TITLE
Web Interface - Toggle Play/Pause

### ISSUE THREAD

**Issue by mneimeyer** [adammhaile/Elpis#59]
Looking in WebInterface.cs I see that you can Play or Pause but that there isn't a command to Toggle the current state.

Ideally I'd like to be able to program a single key on my keyboard that would be able to play when the music is paused and pause if the music is playing (My keyboard has a single key with a >|| icon on it... and not separate play and pause keys.)

Thanks!

**Comment by seliver** [comment]
I see. Will make a commit with this in a minute.

**Comment by seliver** [comment]
Restart Elpis and you should receive the Beta update with the toggleplaypause option ;) Don't forget to tick "Check for beta updates" on settings page.

**Comment by mneimeyer** [comment]
That was... Um... Really quick! :)

Thanks a million!
