### ISSUE TITLE
Intermittent - only part of the song loads

### ISSUE THREAD

**Issue by ssalowitz** [adammhaile/Elpis#63]
Intermittent issue that starts to load the whole song but only plays a few seconds then advances to the next.  See video below

https://drive.google.com/file/d/0BxJjaCFuo-5LMmJoaEt2ZGxFY2s/view?usp=sharing

**Comment by seliver** [comment]
By the look of it I would say that those are most probably ads that 
Pandora embeds into. Can you try using Elpis with another account and 
see if this still happens?

Alexey

Às 13:52 de 25/06/2015, ssalowitz escreveu:

**Comment by ssalowitz** [comment]
I tried with another account and it was not occurring.  It is the type of issue that either it happens during a session or it doesn't.   I have never had it start in mid session. I dont understand what you mean about the ads.  I have never had any ads play on Elpis.

**Comment by seliver** [comment]
If it doesn't happen with another account, then it's not an Elpis issue. You must have probably reached some Pandora invisible limit, like on issue #20 . Give it some time and it will eventually go away.

**Comment by ssalowitz** [comment]
I will keep an eye on it and let you know if it happens with the second account I tried as well.  Since its an intermittent issue its possible that it just didn't happen during that session.  I really love Elpis btw.

**Comment by seliver** [comment]
:+1:

**Comment by seliver** [comment]
Looks like once again it was Pandora's fault. Closing this.
