### ISSUE TITLE
Cannot find an output device matching description - crashes

### ISSUE THREAD

**Issue by jevdemon** [adammhaile/Elpis#68]
Error below.  The output device is plugged in and working normally.
Where does Elpis store its output device preferences?  I wish I could change this default setting so it stops crashing.

BassPlayer.BassException: Cannot find an output device matching description [Headset Earphone (Plantronics C720-M)]
   at BassPlayer.BassAudioEngine.ChangeOutputDevice(String newOutputDevice)
   at Elpis.MainWindow.FinalLoad()

**Comment by seliver** [comment]
Hi @jevdemon. I recommend you to edit the file, deleting the line that starts with "System_OutputDevice" or changing the output device to "Default".
On windows 8 the config file location is C:\Users\<your username>\AppData\Roaming\Elpis , and the file is called elpis.config.

**Comment by jevdemon** [comment]
This fixed the problem.  Thanks for your help.  Thanks also for developing this wonderful app!

**Comment by seliver** [comment]
Glad it helped :+1: Thank you for your feedback :)
