### ISSUE TITLE
Switch to NuGet?

### ISSUE THREAD

**Issue by Litee** [adammhaile/Elpis#70]
Hey,

Did you think about switching some dependencies from plain binaries to NuGet? I could help to do it unless there is some logic behind leaving things as they are now.

**Comment by seliver** [comment]
What would one benefit from this?

**Comment by Litee** [comment]
* No need to include binaries into repository
* Easy to upgrade libraries

**Comment by seliver** [comment]
I see. As far as I know, there are no strict dependencies on executables. It would be great if you can help me on it though :)

**Comment by Litee** [comment]
Sure. Just one question - I can see the whole Kayak library source code included into Elpis - did you make some customizations or it is just for reference?

**Comment by seliver** [comment]
I'm almost sure that I just use it as a reference. Try and see if it works :)

**Comment by seliver** [comment]
done in v1.5.1
