### ISSUE TITLE
"Thumb Up" hot key should work in one direction only

### ISSUE THREAD

**Issue by Litee** [adammhaile/Elpis#72]
Hi,

I like to listen Pandora while working and mark songs that I like by pressing global hot key. Unfortunately if I am trying to like song that I already marked so some time ago it switches back to "unlike". IMO "Thumb Up" key should do nothing if song is already marked with heart. In rare case when I want to "unlike" - I can do it via UI.

**Comment by seliver** [comment]
Good point. 
Have seen this "issue" as well. So basically the unlike is better only to work in the UI and not on the hotkeys nor the API. Will add in a future release.
