### ISSUE TITLE
Updating Bug

### ISSUE THREAD

**Issue by sulmanshah** [adammhaile/Elpis#75]
Operating System: Windows 7

Current Elpis Version: 1.5.0.0

Using proxy/vpn: No

Steps to reproduce the problem: Update from previous version of Elpis

Problem: While updating to the newer version, it does not kill the Elpis process in Windows 7 automatically; users have to open task manager and kill it manually; upon initial launch of the the updated application it freezes the entire machine and user has to do a hard reset of the entire system.

**Comment by seliver** [comment]
I have already seen this issue on updating but have never experienced the machine freezing. Strange. But indeed the first issue has to be fixed.

----- Mensagem Original -----
De: "sulmanshah" <notifications@github.com>
Enviado: ‎04/‎08/‎2015 17:14
Para: "adammhaile/Elpis" <Elpis@noreply.github.com>
Assunto: [Elpis] Updating Bug (#75)

Operating System: Windows 7
Current Elpis Version: 1.5.0.0
Using proxy/vpn: No
Steps to reproduce the problem: Update from previous version of Elpis
Problem: While updating to the newer version, it does not kill the Elpis process in Windows 7 automatically; users have to open task manager and kill it manually; upon initial launch of the the updated application it freezes the entire machine and user has to do a hard reset of the entire system.
