### ISSUE TITLE
Elpis crashes if output device is not found.

### ISSUE THREAD

**Issue by action0jackson** [adammhaile/Elpis#77]
Ideally if the output device is not found a user should have the ability to go into settings and change the device, or Elpis should try and use the default device.  To circumvent the issue I went into the config file and just removed the device listed and then the program loaded.

**Comment by seliver** [comment]
This is already mentioned in issue #67. And indeed it's a bug that needs to be dealt.

**Comment by action0jackson** [comment]
Sorry, I looked through the bugs prior to logging this to make sure it wasn't a dup.  I opened up issue #67 and it doesn't appear to be the same issue, unless I'm missing something. I see no reference to output audio device.  But I'll take your word for it if the underlying issue is the same, although I believe the error message is different.  I'll capture that if you'd like.

**Comment by seliver** [comment]
Fixed my post. Sorry about that.

**Comment by action0jackson** [comment]
Perfect thanks, since it's logged you can go ahead and close this issue.

**Comment by seliver** [comment]
I'll leave this one open in case anyone else gets this problem. And also to be able to include this issue on the milestone. Thanks for your feedback :+1:

**Comment by action0jackson** [comment]
Anytime...I love this app!  It helps me get through my days at work.  ;)

**Comment by seliver** [comment]
Temporary solution for this is mentioned in #68 and #87 .
