### ISSUE TITLE
Install interrupted

### ISSUE THREAD

**Issue by mbrazil** [adammhaile/Elpis#79]
I'm trying to install ver. 1.5.0 and I get the following every time:

![elpis](https://cloud.githubusercontent.com/assets/10537299/9159694/7962f148-3ee2-11e5-8ba5-5d6e7b83181a.png)

**Comment by seliver** [comment]
Tell us more information about your system. What's your windows version? Have you already installed Elpis before? Have you got .net installed?

----- Mensagem Original -----
De: "mbrazil" <notifications@github.com>
Enviado: ‎10/‎08/‎2015 06:04
Para: "adammhaile/Elpis" <Elpis@noreply.github.com>
Assunto: [Elpis] Install interrupted (#79)

I'm trying to install ver. 1.5.0 and I get the following every time:

**Comment by mbrazil** [comment]
I'm still running XP SP3 (but not for much longer). I'd been running an earlier version of Elpis (I uninstalled it to try to get the 1.5.0 installer to work right, so I don't know which version it was) for at least a year. .net 1 through 4 are installed. The first time I ran the 1.5.0 installer, I didn't get that message, and it seemed to go through the first part of the installation process correctly. After the reboot, I got a message (unfortunately, I didn't make a copy of it, so I don't know if it's the same one I'm getting now), and since then, I get the message I posted every time I run the installer. I uninstalled Elpis using Revo Uninstaller Pro and tried again, but that didn't help.


Mike
  ----- Original Message -----

**Comment by mneimeyer** [comment]
I am seeing this as well on XP SP3 with all the post-SP3 fixes I can get from Windows Update applied.

That said, I didn't report it here because I my XP install was built using nLite to make a compact XP to fit on a small solid state disk in a WYSE embedded XP device and I assumed I broke something Elpis needed when I was removing parts of XP.

As to .NET I have 1.1, 2.0 SP2, 3.0 SP2, 3.5 SP1 and 4 Client Profile installed (looking at Add or Remove Programs)

**Comment by seliver** [comment]
Please try installing .Net 4.5. Maybe it will solve the issue.

**Comment by mbrazil** [comment]
The .NET 4.5 installer says it's not supported on XP (actually, it says "this operating system") and won't install.

Mike
  ----- Original Message -----

**Comment by seliver** [comment]
Try downloading the portable version: https://github.com/adammhaile/Elpis/releases/tag/1.5.0
Just unzip the folder and try if it works.

**Comment by mbrazil** [comment]
Thanks!!

The portable version seems to work fine. Are there any drawbacks to running the portable version compared to the installed version?

Mike
  ----- Original Message -----

**Comment by seliver** [comment]
I don't think so. What I did was to zip the Elpis folder installed on my PC.

----- Mensagem Original -----
De: "mbrazil" <notifications@github.com>
Enviado: ‎14/‎08/‎2015 22:29
Para: "adammhaile/Elpis" <Elpis@noreply.github.com>
Cc: "seliver" <alexeyseliverstov.dev@gmail.com>
Assunto: Re: [Elpis] Install interrupted (#79)

Thanks!!

The portable version seems to work fine. Are there any drawbacks to running the portable version compared to the installed version?

Mike
----- Original Message -----
