### ISSUE TITLE
Compilation Warnings

### ISSUE THREAD

**Issue by gundermanc** [adammhaile/Elpis#83]
Operating System: 
Windows 10 - Visual Studio 2015 Community

Current Elpis Version: 
Current Master Branch

Using proxy/vpn:
No

Steps to reproduce the problem:
Compile with Visual Studio 2015

Problem: 
Many Compiler Warnings during Elpis Compilation for unused variables and malformed comments.

**Comment by seliver** [comment]
Just installed visual studio 2015, will check it out.

**Comment by seliver** [comment]
Not a problem. Closing.
