### ISSUE TITLE
Does not detect if startup location is on screen

### ISSUE THREAD

**Issue by firecruiser** [adammhaile/Elpis#88]
OS: Windows 7 and 10
Version 1.5
Not using proxy

Steps to reproduce:
1. Launch Elpis
2. Move Elpis to the sceeen farthest from the primary screen.
3. Close Elpis
4. Adjust screen settings to move the screen elpis was on such that the screen coordinate is no longer on screen.
5. Launch Elpis.

Problem:
Elpis launches with the previous screen location stored in the config file, however, the location is not verified if it is on screen. This causes elpis to be lost offscreen. Since Elpis does not use the window manager border win+arrow doesn't move the elpis window.

**Comment by firecruiser** [comment]
It looks like there is already a closed issue for the same problem and a commit has been made to fix it.

**Comment by seliver** [comment]
solved on release v1.5.1
