### ISSUE TITLE
Lyrics window

### ISSUE THREAD

**Issue by RingOfStorms** [adammhaile/Elpis#90]
I would love to see a lyrics overlay window similar to
https://chrome.google.com/webstore/detail/gaana-lyrics-extension/indphkjgcbdoaigcjlaaokkfllleolli?utm_source=chrome-app-launcher-info-dialog
for the chrome browser.

The extension is powered by LyricWiki which has an API that can be implemented, and when a song is not found it shows very useful links to LyrikWiki that let you easily put the lyrics in and update them.

I would love to see some kind of option to have an always on top, semi-transparent (configurable?) window that you can keep up that acts similar to the app I linked above.

**Comment by janabimustafa** [comment]
To bring this back to life, there is a track.getLyrics method in their JSON api. I am trying to figure out what it accepts. Passing only trackToken shoots back error 9 (not enough parameters).

**Comment by seliver** [comment]
maybe timestamp?

**Comment by janabimustafa** [comment]
Oh sorry. I meant track Token along with all the other boilerplate properties such as the timestamp and Auth.

**Comment by seliver** [comment]
how's it going?
