### ISSUE TITLE
Enhancement Request: Now Playing File

### ISSUE THREAD

**Issue by mneimeyer** [adammhaile/Elpis#93]
Other media players I use can create a text file that contains track information about the currently playing file along with the state. I use this file to output to a small LCD what is playing... I'd love to see something like this for Elpis.

Output might look like...

> Elpis status: Playing
> Station: My Cool Station
> Track: Some Cool Song
> Album: Some Cool Album
> Artist: My Favorite Singer

Swapping out Playing for Paused or "Not Running" (which would be written when Elpis is closed)

Maybe even the url / file name of the cover art.

Thanks!

**Comment by seliver** [comment]
Well, currently Elpis has got an HTTP Api that does exactly this. Check it out and how to use it on the wiki https://github.com/adammhaile/Elpis/wiki/HTTP-Api
