### ISSUE TITLE
last.fm token expired

### ISSUE THREAD

**Issue by kingofzeal** [adammhaile/Elpis#96]
When attempting to link the last.fm scrobbler, I get the following error from last.fm:

Token expired. Please return to Elpis and try again.

**Comment by seliver** [comment]
Will have a look at whats going on with it.

**Comment by adammhaile** [comment]
Might be the elpis api token expired? I'll try to check on it... I think
that's still on my accounts.

**Comment by seliver** [comment]
I think so, yes.

**Comment by adammhaile** [comment]
Yeah.. my account expired. You'll need to register a new token here:
http://www.last.fm/api

**Comment by Raputo** [comment]
I cannot scrobble at the moment using Elpis. Is it being worked on?

**Comment by seliver** [comment]
Yes it is. Sorry for the delay. 
A new beta will be released, can you test if the Scrobble works?

**Comment by seliver** [comment]
Here'ya go, version 1.5.2 with scrobbler. Please test and give feedback. Thanks!

**Comment by Raputo** [comment]
Hey thanks! Works wonderfully now!

**Comment by seliver** [comment]
nice!

**Comment by seliver** [comment]
Looks like this is solved. Closing this.
