### ISSUE TITLE
Unknown software exception on startup

### ISSUE THREAD

**Issue by Drakedude** [adammhaile/Elpis#97]
Elpis worked well at first, but now on startup i get a popup window called "SystemResourceNotifyWindow:Elpis.exe" and this error message:

"The exception unknown software exception (0xe0434352) occurred in the application at location 0x0000000076833E28"

After closing the window, EIpis won't open. I've uninstalled and reinstalled Elpis and the problem persists.

**Comment by seliver** [comment]
Try deleting the configuration files. They're located at 
C:\Users\<YOUR_USERNAME>\AppData\Roaming\Elpis

The file to rename(just in case you might need the old configuration) is 
the elpis.config
After that just try to open Elpis again.

Alexey

Às 14:22 de 25/10/2015, Drakedude escreveu:

**Comment by Drakedude** [comment]
:)
